### ISSUE TITLE
[Bug] tenant memory allocation in main thread will skip check before allocate

### ISSUE THREAD

**Issue by XHao** [alibaba/dragonwell8#103]
**Description**
When enable mult-tenant feature, and run the task in main thread. It will skip size check before allocate.
Is it a feature or bug? I can't find any document about this.

**Steps to Reproduce**
1. Enable MultiTenant feature with `-XX:+MultiTenant -XX:+TenantHeapThrottling -XX:+UseG1GC`
2. sample code
```
public static void main(String[] args) {
        Iterable<Constraint> constraints = Stream.of(ResourceType.HEAP_RETAINED.newConstraint(10 * MEGABYTE))
                .collect(Collectors.toList());
        ResourceContainer tenant = TenantContainerFactory.instance().createContainer(constraints);
        tenant.run(() -> {
            // new Thread(() -> { // open a new thread will throw oom
                try {
                    byte[] bytes = new byte[(int) (10 * MemoryEat.MEGABYTE)];
                    System.out.println(new String(bytes));
                } catch (Throwable t) {
                    t.printStackTrace();
                }
            // }).start();
        });
    }
```
I guess:

Task in main thread will not invoke `TenantContainer.attach()` so `context.is_system()` is true

**Expected behavior**
thow oom exception
Or 
update the document about this feature

**JDK version**
8.3.3

**Execution environment**
 - OS and version: Linux
 - CPU model: x64
 - Number of CPU cores:any
 - Size of physical memory:any
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by luchsh** [comment]
Thanks for reporting! will have a look.

**Comment by tanghaoth90** [comment]
Hi @XHao , thanks for reporting!

You can leverage HeapThrottling feature by `TenantContainer.create(config)` API by far. See `testHumongousLimit` in `hotspot/test/multi-tenant/TestTenantHeapLimit.java`.

```
private static void testHumongousLimit() {
    TenantConfiguration config = new TenantConfiguration().limitHeap(HEAP_REGION_SIZE * 100);
    TenantContainer tenant = TenantContainer.create(config);

    System.gc();

    try {
        tenant.run(()->{
            try {
                // create a humongous object whose size > tenant heap limit
                Object obj = new byte[(int) (config.getMaxHeap() * 2)];
                // should throw OOM
                fail();
            } catch (OutOfMemoryError oom) {
                // expected!
            } catch (Throwable e) {
                System.err.println("Unexpected exception!");
                e.printStackTrace();
                fail();
            }
        });
    } catch (TenantException e) {
        fail();
    }
}
```

Furthermore, you are right. The sample code that you provided should have thrown OOM exception. That is because `com.alibaba.tenant.TenantResourceContainer` does not support memory limitation in the latest version. We are going to support memory limitation in the near future.

**Comment by XHao** [comment]
Ok, I get it now, thanks! 😄

**Comment by colin-xun** [comment]
@tanghaoth90 
The code you provided can't achieve the expected effect when running on my machine, it will not throw an OutOfMemoryError


LSB Version:	security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial
arch：x86_64
