### ISSUE TITLE
Does dragonwell have JRE version or not?

### ISSUE THREAD

**Issue by chenweiyj** [alibaba/dragonwell8#104]
Since the runtime docker image only needs jre, we prefer to see the dragonwell provides an alpine jre version image. Can dragonwell provide the JRE version?

**Comment by luchsh** [comment]
The 'slim' images are pretty compact as I see, like 
`registry.cn-hangzhou.aliyuncs.com/dragonwell/dragonwell8:8.3.3-GA_alpine_x86_64_8u242-b98_slim`
many unnecessary artifacts were removed, pls have a try :)

**Comment by luchsh** [comment]
> The 'slim' images are pretty compact as I see, like
> `registry.cn-hangzhou.aliyuncs.com/dragonwell/dragonwell8:8.3.3-GA_alpine_x86_64_8u242-b98_slim`
> many unnecessary artifacts were removed, pls have a try :)

I was assuming the primary reason to request a JRE based image is to reduce the image size, right? in that case, the 'slim' images may be a good fit.
