### ISSUE TITLE
[Bug]  An error caused the java process to automatically exit after running for a period of time.

### ISSUE THREAD

**Issue by yaojunWang** [alibaba/dragonwell8#106]
**Description**
 An error caused the java process to automatically exit after running for a period of time.
OS version is "Ubuntu 20.04 Server(On Aliyun)".
The only  error log message is  " /usr/local/j2sdk-image/bin/java: symbol lookup error: /lib/x86_64-linux-gnu/libfontconfig.so.1: undefined symbol: FT_Done_MM_Var"

**Steps to Reproduce**
1. Download "Alibaba_Dragonwell_8.3.3-GA_Linux_x64.tar.gz" and  decompress  to /usr/local/j2sdk-image,set JAVA_HOME and PATH  variables
2. Download tomcat9.0.36 and unzip to /usr/lib/tomcat9
3. Execute  start.sh to start tomcat 
4. See error log and tomcat process exit after running for a period of time(hours)
5. Restart tomcat, this problem will still occur after a few hours

**JDK version**
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.3.3) (build 1.8.0_242-b98)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.3.3) (build 25.242-b98, mixed mode)

**Execution environment**
 - OS and version:  LSB Version:    core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch  Description:    Ubuntu 20.04 LTS
 - CPU model:Intel(R) Xeon(R) Platinum 8163 CPU @ 2.50GHz  
 - Number of CPU cores:4
 - Size of physical memory:16G

**Comment by kuaiwei** [comment]
Thanks for your report.
From the error message, it looks an error in libfontconfig or libfreetype. Could you check if the symbol "FT_Done_MM_Var" exists in these 2 shared objects?

Kuai Wei

**Comment by yaojunWang** [comment]
Thanks for reply, here is the check result:
```
root@xxxxxxxx:~$ mlocate libfontconfig
/usr/lib/x86_64-linux-gnu/libfontconfig.so.1
/usr/lib/x86_64-linux-gnu/libfontconfig.so.1.12.0
/usr/share/doc/libfontconfig1
/usr/share/doc/libfontconfig1/changelog.Debian.gz
/usr/share/doc/libfontconfig1/copyright
/var/cache/apt/archives/libfontconfig1_2.13.1-2ubuntu3_amd64.deb
/var/lib/dpkg/info/libfontconfig1:amd64.list
/var/lib/dpkg/info/libfontconfig1:amd64.md5sums
/var/lib/dpkg/info/libfontconfig1:amd64.shlibs
/var/lib/dpkg/info/libfontconfig1:amd64.symbols
/var/lib/dpkg/info/libfontconfig1:amd64.triggers
root@xxxxxxxx:~$ cat /var/lib/dpkg/info/libfontconfig1\:amd64.symbols | grep FT_Done_MM_Var
root@xxxxxxxx:~$ 
root@xxxxxxxx:~$ mlocate libfreetype
/usr/lib/x86_64-linux-gnu/libfreetype.so.6
/usr/lib/x86_64-linux-gnu/libfreetype.so.6.17.1
/usr/share/doc/libfreetype6
/usr/share/doc/libfreetype6/README
/usr/share/doc/libfreetype6/changelog.Debian.gz
/usr/share/doc/libfreetype6/copyright
/var/lib/dpkg/info/libfreetype6:amd64.list
/var/lib/dpkg/info/libfreetype6:amd64.md5sums
/var/lib/dpkg/info/libfreetype6:amd64.shlibs
/var/lib/dpkg/info/libfreetype6:amd64.symbols
/var/lib/dpkg/info/libfreetype6:amd64.triggers
root@xxxxxxxx:~$ cat /var/lib/dpkg/info/libfreetype6\:amd64.symbols | grep FT_Done_MM_Var
 FT_Done_MM_Var@Base 2.9.1
root@xxxxxxxx:~# 
```

**Comment by kuaiwei** [comment]
I will try to reproduce the error. Could you provide hs_err log to troubleshooting?

**Comment by kuaiwei** [comment]
I run 2 tests but failed to reproduce it.
1 Run DraongWell8.3.3GA+Tomcat9.0.36, it run for 10+ hours no error.
2 Install libfontconfig and run test again, java process has run for 6 hours no error.
Do you deploy other web app in tomcat?

**Comment by yaojunWang** [comment]
Yes, I run a normal Web application with font-related code in it. I copied the font from the Windows 7 font library to Ubuntu. There is no has_err log file, only the above error is printed in the Tomcat catalina.out log file.Here is the code( I should have found the reason, it was happened after visiting this code).
```
BufferedImage bi = ImageIO.read(AdminBaseApplication.class.getClassLoader().getResourceAsStream("module.png"));
Graphics g = bi.getGraphics();
g.setFont(new Font("宋体", Font.BOLD, 36));
g.setColor(Color.black);
g.drawString(user.getNikeName()+":", 120, 330);
g.setFont(new Font("宋体", Font.BOLD, 24));
Calendar c = Calendar.getInstance();
c.setTime(paper.getEndTime());
g.drawString("身份证号("+user.getIdNumber()+"),于"+new SimpleDateFormat("yyyy年MM月dd日,").format(c.getTime()), 210, 390);
c.add(Calendar.YEAR, 1);
c.add(Calendar.DATE, -1);
g.drawString("XXXXXXX合格.有效期至" + new SimpleDateFormat("yyyy年MM月dd日.").format(c.getTime()), 120, 430);
g.drawString("证书编号:" + paper.getId().replaceAll("-", "").toUpperCase(), 200, 1180);
g.dispose();
ImageIO.write(bi, "png", resp.getOutputStream());
```
