### ISSUE TITLE
请问是否有可以用于生产的8u252版本？

### ISSUE THREAD

**Issue by BIG-CHEF** [alibaba/dragonwell8#107]
我在releases中看到了8u252-b06版本，并不是ga的版本

**Comment by BIG-CHEF** [comment]
另外我在releases中看到8u242几乎每个b版本都有个release，怎么理解这些包的存在？

**Comment by luchsh** [comment]
> 另外我在releases中看到8u242几乎每个b版本都有个release，怎么理解这些包的存在？

你是在github->Code->Releases里面看到的吗？8u242-b*的包是github 根据每一个tag自动生成的，不是阿里做得发布。
阿里做的正式发布是那些包含了各个平台二进制文件的release，可以在wiki里面找，更容易一些。
https://github.com/alibaba/dragonwell8/wiki/Alibaba-Dragonwell8-Release-Notes

**Comment by luchsh** [comment]
> 我在releases中看到了8u252-b06版本，并不是ga的版本

Dragonwell 8 的正式release都是打了“dragonwell-8.\d+.\d+-GA” 模式的tag的

**Comment by BIG-CHEF** [comment]
感谢答复
