### ISSUE TITLE
[Merge] Merge OpenJDK 8u262-ga

### ISSUE THREAD

**Issue by D-D-H** [alibaba/dragonwell8#108]
**Description**
This task is for merging openjdk8u262-ga
Main actions:
1. reverted the old JFR implementation in Dragonwell
2. merged openjdk8u262-ga, there were only a few conflicts and all of them could be resolved clearly
   - https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-July/012143.html
3. fixed hotspot & JDK test failures, see
    - https://github.com/alibaba/dragonwell8_hotspot/pull/36/commits/7dee1fe51a9f32d4d5a4868fddddacad01302214
    - https://github.com/alibaba/dragonwell8_jdk/pull/16/commits/45776c14c10651acb947f9b20995ba8afb8c131a
4. fixed build failure on Windows
    - https://github.com/alibaba/dragonwell8/pull/109/commits/67b61c6e0e56758267478e5986d3abb7fc762088

**Steps to Reproduce**

**Expected behavior**

**JDK version**

**Execution environment**
 - OS and version:
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by alijvm** [comment]
Pls. add the detail info in your summary to describe the major change in this merge.

**Comment by sanhong** [comment]
This task is to merge jdk8u262-ga,  it is too general.
pls. describe the major changes in our side,  for exmaple, remove Alibaba-specific JFR changes.

**Comment by sanhong** [comment]
Just make sure your submit pass the check-commit.  you can leave all build_* checks AS-IS.

**Comment by sanhong** [comment]
there were only a few minor conflicts, so omit the conflicts here --> there were only a few minor conflicts
"so omit the conflicts here"   -  is a little confusing.

**Comment by D-D-H** [comment]
> This task is to merge jdk8u262-ga, it is too general.
> pls. describe the major changes in our side, for exmaple, remove Alibaba-specific JFR changes.

added

**Comment by D-D-H** [comment]
> there were only a few minor conflicts, so omit the conflicts here --> there were only a few minor conflicts
> "so omit the conflicts here" - is a little confusing.

refined
