### ISSUE TITLE
[Bug] crash:AddNode::Ideal(PhaseGVN*, bool)

### ISSUE THREAD

**Issue by yansendao** [alibaba/dragonwell8#11]
**Description**
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fba9132e4ff, pid=1023671, tid=0x00007fb85dd64700
#
# JRE version: OpenJDK Runtime Environment (8.0_202-b30) (build 1.8.0_202-b30)
# Java VM: OpenJDK 64-Bit Server VM (25.202-b30 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x2bf4ff]  AddNode::Ideal(PhaseGVN*, bool)+0x1af
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
```

**Steps to Reproduce**
1. Save below snippet '...'
2. Compile it with javac '....'
3. Execute with VM options '....'

**Expected behavior**

**JDK version**
The output of `java -version` command
```
$ ./j2sdk-image/bin/java -version ; ./j2sdk-image/bin/java -Xinternalversion
openjdk version "1.8.0_202"
OpenJDK Runtime Environment (Dragonwell 8.0-preview) (build 1.8.0_202-b30)
OpenJDK 64-Bit Server VM (Dragonwell 8.0-preview) (build 25.202-b30, mixed mode)
OpenJDK 64-Bit Server VM (25.202-b30) for linux-amd64 JRE (1.8.0_202-b30), built on Mar 20 2019 18:29:49 by "admin" with gcc 4.4.7
```

**Execution environment**
 - OS and version:
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:
```
$ cat /etc/issue ; uname -a ; lscpu ; nproc ; free -h
Ubuntu 16.04 LTS \n \l

Linux mathine-ysd 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                144
On-line CPU(s) list:   0-143
Thread(s) per core:    2
Core(s) per socket:    18
Socket(s):             4
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 63
Model name:            Intel(R) Xeon(R) CPU E7-8890 v3 @ 2.50GHz
Stepping:              4
CPU MHz:               2499.902
CPU max MHz:           3300.0000
CPU min MHz:           1200.0000
BogoMIPS:              4990.09
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              46080K
NUMA node0 CPU(s):     0-17,72-89
NUMA node1 CPU(s):     18-35,90-107
NUMA node2 CPU(s):     36-53,108-125
NUMA node3 CPU(s):     54-71,126-143
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm xsaveopt cqm_llc cqm_occup_llc dtherm arat pln pts
144
              total        used        free      shared  buff/cache   available
Mem:           503G        8.3G        288G        1.0G        207G        492G
Swap:           19G        369M         18G
```

**Comment by kuaiwei** [comment]
Could you provide the reproducible test case? And do you test with OpenJDK before?

Thanks

**Comment by yansendao** [comment]
[testfile.zip](https://github.com/alibaba/dragonwell8/files/2991439/testfile.zip)

```
javac Test.java
java Test
```

**Comment by luchsh** [comment]
OpenJDK8u202b08 fails with this testcase either.
I'd like to suggest you to submit this case to the upstream OpenJDK bug tracking system,
https://bugs.openjdk.java.net/

alternatively, Dragonwell community may help to raise OpenJDK bugs with your consent.
Thanks!

**Comment by yansendao** [comment]
Dragonwell community can help me to raise OpenJDK bugs and then close this issue. Thanks very much.

**Comment by luchsh** [comment]
OpenJDK bug created, will monitor and ask for backporting when upstream has got a patch, thanks!
https://bugs.openjdk.java.net/browse/JDK-8221603

**Comment by luchsh** [comment]
@yansendao  do you plan to contribute the testcase to Dragonwell?
In that case, CLA must be signed:
https://cla-assistant.io/alibaba/dragonwell8

If you are an individual contributor, pls sign the "Alibaba Documentation Individual Contributor License Agreement".
If you are representing a company, like Huawei, please sign the "Alibaba Documentation Corporate Contributor License Agreement".

**Comment by yansendao** [comment]
> @yansendao do you plan to contribute the testcase to Dragonwell?
> In that case, CLA must be signed:
> https://cla-assistant.io/alibaba/dragonwell8
> 
> If you are an individual contributor, pls sign the "Alibaba Documentation Individual Contributor License Agreement".
> If you are representing a company, like Huawei, please sign the "Alibaba Documentation Corporate Contributor License Agreement".

已经通过github网页签署协议。用例可以贡献给Dragonwell社区，提交issue仅仅是个人行为，不代表任何组织或公司。
