### ISSUE TITLE
[Misc] Test failure: jdk/test/com/sun/jdi/StepTest.java

### ISSUE THREAD

**Issue by D-D-H** [alibaba/dragonwell8#111]
**Description**

**Steps to Reproduce**
1. Save below snippet '...'
2. Compile it with javac '....'
3. Execute with VM options '....'

**Expected behavior**

**JDK version**
The output of `java -version` command

**Execution environment**
 - OS and version:
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by joeyleeeeeee97** [comment]
Step to reproduce this:
http://ci.dragonwell-jdk.io/job/Test_openjdk8_hs_sanity.openjdk_x86-64_linux/31/testReport/junit/com_sun_jdi_StepTest/java/StepTest/
