### ISSUE TITLE
[Misc] Make EnableJFR obsolete

### ISSUE THREAD

**Issue by D-D-H** [alibaba/dragonwell8#119]
Old JFR implementation was removed, we should make EnableJFR obsolete.

**Comment by ghu212** [comment]
新人使用，按照文档里的-XX:+EnableJFR配置，一直报错，查了很久才发现8.4.4版本已经标记过期了，后续版本直接删除了。那么也请把文档里有关JFR的部分也更新一下，避免误导人，谢谢！

**Comment by D-D-H** [comment]
@ghu212 
抱歉造成你们的困扰。
EnableJFR 过期之后理论上不应该被删除。
我看了下提交记录，这个过期参数是在 Merge 272u 中被误删除了。

我更新下文档。
https://github.com/alibaba/dragonwell8_hotspot/commit/a1a50a737276f58d9f52d1ae51afd7715ed65185#diff-b1d4f443783e9566820eb451f0c36dfd9d938a16298036896dec6c4c58718160

我更新下文档。

**Comment by D-D-H** [comment]
> 新人使用，按照文档里的-XX:+EnableJFR配置，一直报错，查了很久才发现8.4.4版本已经标记过期了，后续版本直接删除了。那么也请把文档里有关JFR的部分也更新一下，避免误导人，谢谢！

文档已更新，感谢反馈。
