### ISSUE TITLE
Alibaba Dragonwell 8.4.4 GA 的版本信息还是 Alibaba Dragonwell 8.3.3

### ISSUE THREAD

**Issue by zja0918** [alibaba/dragonwell8#121]
下载 https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.4.4_jdk8u262-ga/Alibaba_Dragonwell_8.4.4-Experimental_Windows_x64.tar.gz

java -version

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.3.3) (build 1.8.0_242-b00)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.3.3) (build 25.242-b00, mixed mode)

**Comment by zhengxiaolinX** [comment]
Thanks for reporting! I've released a new version including the newest build number, which can be downloaded via [oss](https://dragonwell.oss-cn-shanghai.aliyuncs.com/8/8.4.4-GA/Alibaba_Dragonwell_8.4.4-Experimental_Windows_x64.tar.gz) or [github](https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.4.4_jdk8u262-ga/Alibaba_Dragonwell_8.4.4-Experimental_Windows_x64.tar.gz).
It seems that our Windows platform build procedure should get an enhancement.
Also please have a check, and feel free to reopen this issue.
