### ISSUE TITLE
可能与Netty存在冲突

### ISSUE THREAD

**Issue by crazythinking** [alibaba/dragonwell8#122]
**Description**

**Steps to Reproduce**
开启wisp2参数后，发现凡是依赖netty的服务存在问题，具体现象为：可以正常启动，但是凡是涉及通过netty走nio进行远程访问时，访问不通，长时间handle无响应；

**Expected behavior**
未抛出异常；

**JDK version**
使用8.4.4版本

**Execution environment**
 - OS and version: CentOS 7
 - CPU model: x86
 - Number of CPU cores: 4c
 - Size of physical memory: 8g
 - Inside Linux container? 虚机，非容器

**Comment by joeyleeeeeee97** [comment]
wisp通过在线程进入阻塞的逻辑处添加进入协程调度的逻辑来进行透明切换，netty 框架中 的JNI中的无法切换。

请尝试下使用 -Dio.netty.noUnsafe=true 来强制netty 使用 Nio而非netty transport里面的epoll.

**Comment by yuleil** [comment]
请参考文档的这部分 https://github.com/alibaba/dragonwell8/wiki/Wisp-Documentation#limitations
如果依旧无法解决，请提供完整的jstack，或者`jstack PID | grep Wisp-Root -A 20`

Please refer to this part of the document https://github.com/alibaba/dragonwell8/wiki/Wisp-Documentation#limitations
If it still not work, please provide the complete jstack or `jstack PID | grep Wisp-Root -A 20` to us

**Comment by crazythinking** [comment]
多谢两位，-Dio.netty.noUnsafe=true不行，但通过-Dio.netty.transport.noNative=true可以解决。
