### ISSUE TITLE
钉钉群无法加入

### ISSUE THREAD

**Issue by colin-xun** [alibaba/dragonwell8#125]
我对该项目很感兴趣，想加入钉钉群沟通一下，但是钉钉群只能群主拉取，怎么可以加入呢？

**Comment by opjk** [comment]
同上，加入不了群聊。

**Comment by yuleil** [comment]
![image](https://user-images.githubusercontent.com/4951569/92114426-668cf000-ee23-11ea-9527-167190e4e363.png)
二维码过去，请使用新的码
