### ISSUE TITLE
[Bug] crash:SuperWord::get_pre_loop_end(CountedLoopNode*)

### ISSUE THREAD

**Issue by yansendao** [alibaba/dragonwell8#13]
**Description**
```
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fbaf195dedb, pid=1021938, tid=0x00007fb8bdd64700
#
# JRE version: OpenJDK Runtime Environment (8.0_202-b30) (build 1.8.0_202-b30)
# Java VM: OpenJDK 64-Bit Server VM (25.202-b30 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0xa53edb]  SuperWord::get_pre_loop_end(CountedLoopNode*)+0x6b
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
```

**Steps to Reproduce**
1. Save below snippet '...'
2. Compile it with javac '....'
3. Execute with VM options '....'

**Expected behavior**

**JDK version**
The output of `java -version` command

**Execution environment**
 - OS and version:
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by kuaiwei** [comment]
Could you provide the reproducible test case? And do you test with OpenJDK before?

Thanks

**Comment by yansendao** [comment]
```
javac Test.java
java Test
```

[testfile.zip](https://github.com/alibaba/dragonwell8/files/2991470/testfile.zip)

**Comment by luchsh** [comment]
OpenJDK8u202b08 fails with this testcase either.
I'd like to suggest you to submit this case to the upstream OpenJDK bug tracking system,
https://bugs.openjdk.java.net/

alternatively, Dragonwell community may help to raise OpenJDK bugs with your consent.
btw, thumbs up for this fine testing job!

Thanks!

**Comment by yansendao** [comment]
Dragonwell community can help me to raise OpenJDK bugs and then close this issue. Thanks very much.

**Comment by luchsh** [comment]
@yansendao  do you plan to contribute the testcase to Dragonwell?
In that case, CLA must be signed:
https://cla-assistant.io/alibaba/dragonwell8

If you are an individual contributor, pls sign the "Alibaba Documentation Individual Contributor License Agreement".
If you are representing a company, like Huawei, please sign the "Alibaba Documentation Corporate Contributor License Agreement".

**Comment by yansendao** [comment]
> @yansendao do you plan to contribute the testcase to Dragonwell?
> In that case, CLA must be signed:
> https://cla-assistant.io/alibaba/dragonwell8
> 
> If you are an individual contributor, pls sign the "Alibaba Documentation Individual Contributor License Agreement".
> If you are representing a company, like Huawei, please sign the "Alibaba Documentation Corporate Contributor License Agreement".

已经通过github网页签署协议。用例可以贡献给Dragonwell社区，提交issue仅仅是个人行为，不代表任何组织或公司。
