### ISSUE TITLE
开发计划

### ISSUE THREAD

**Issue by opjk** [alibaba/dragonwell8#131]
Dragonwell  最新发布 8.4.4 版本还是基于 openjdk version "1.8.0_262"，而 openjdk   15 已经发布了，虽然8.4.4版本中有很多新的openjdk中的功能，但不是全部，是否有计划 与 后续的 openjdk 新版功能同步？

能否列出，与最新发布 的 openjkd  15版本中特性差异？

**Comment by joeyleeeeeee97** [comment]
您好.
Dragonwell 8 和 11 会在每次GA 发布之前rebase openjdk的GA.
除去dragonwell研发的特性外, dragonwell8的特性会和openjdk8 一致.

**Comment by luchsh** [comment]
> 这条是非官方评论：
我猜您可能不太清楚JDK的大版本是什么意思、是怎样演进的，可以多读OpenJDK官网。
版本差异的话openjdk和dragonwell的release notes里面都有写啊，可以自己去查阅嘛。

**Comment by zhengxiaolinX** [comment]
Thank you for opening this issue but, there are seven big versions between JDK8 and JDK15, and most features of Dragonwell8 share the same with OpenJDK8. Comparing with these two versions doesn't make sense theoretically. I'd close it first and please feel free to reopen it.
