### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by googleweb** [alibaba/dragonwell8#133]
操作系统：ubuntu 16.04
同样环境，编译openjdk正常。
dragonwell8到这里可以编译出java程序，只是允许其他程序的时候提示找不到系统类库，抛出找不到类的异常。

**Comment by googleweb** [comment]
echo  "Linking executable unpack200"
Linking executable unpack200
/usr/bin/gcc -lz -Xlinker -rpath -Xlinker \$ORIGIN/../lib/amd64/jli -Xlinker -rpath -Xlinker \$ORIGIN/../lib/amd64 -Wl,-z,relro -Wl,--build-id=sha -Xlinker --hash-style=both -Xlinker -z -Xlinker defs -Xlinker -z -Xlinker noexecstack -Xlinker -O1 -Xlinker --allow-shlib-undefined -pie -Xlinker -soname=libunpack.so -Xlinker -z -Xlinker origin -Xlinker -rpath -Xlinker \$ORIGIN -lc -Xlinker -version-script=/home/googlewell/dragonwell8/jdk/make/mapfiles/libunpack/mapfile-vers-unpack200  -o /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/unpack200 /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/bands.o /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/bytes.o /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/coding.o /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/main.o /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/unpack.o /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/utils.o /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o  -Wl,-Bstatic -lstdc++ -lgcc -Wl,-Bdynamic   
cd /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jexec_obj && /usr/bin/zip -q /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jexec_obj/jexec.diz jexec.debuginfo
/bin/mkdir -p /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin
/bin/rm -f /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/java
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/java_objs/java /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/java
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/appletviewer_objs/appletviewer.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/appletviewer.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/extcheck_objs/extcheck.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/extcheck.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/idlj_objs/idlj.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/idlj.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jar_objs/jar.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jar.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jarsigner_objs/jarsigner.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jarsigner.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/javac_objs/javac.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/javac.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/javadoc_objs/javadoc.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/javadoc.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/javah_objs/javah.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/javah.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/javap_objs/javap.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/javap.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jdeps_objs/jdeps.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jdeps.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jconsole_objs/jconsole.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jconsole.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jdb_objs/jdb.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jdb.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jhat_objs/jhat.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jhat.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jinfo_objs/jinfo.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jinfo.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jmap_objs/jmap.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jmap.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jps_objs/jps.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jps.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jrunscript_objs/jrunscript.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jrunscript.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jjs_objs/jjs.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jjs.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jsadebugd_objs/jsadebugd.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jsadebugd.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/hsdb_objs/hsdb.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/hsdb.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/clhsdb_objs/clhsdb.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/clhsdb.diz
/bin/cp /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/jstack_objs/jstack.diz /home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/bin/jstack.diz
/usr/bin/ld: warning: unrecognized --build-id style ignored.
/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o：在函数‘jar::deflate_bytes(bytes&, bytes&)’中：
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:466：对‘deflateInit2_’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:509：对‘deflate’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:516：对‘deflateEnd’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:504：对‘deflate’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:520：对‘deflateEnd’未定义的引用
/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o：在函数‘jar::addJarEntry(char const*, bool, int, bytes&, bytes&)’中：
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:61：对‘crc32’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:61：对‘crc32’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:61：对‘crc32’未定义的引用
/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o：在函数‘gunzip::free()’中：
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:647：对‘inflateEnd’未定义的引用
/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o：在函数‘read_input_via_gzip(unpacker*, void*, long, long)’中：
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:550：对‘inflate’未定义的引用
/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o：在函数‘gunzip::start(int)’中：
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:639：对‘inflateInit2_’未定义的引用
collect2: error: ld returned 1 exit status
make[2]: *** [/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/unpack200] Error 1
CompileLaunchers.gmk:489: recipe for target '/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/unpack200' failed
make[2]: *** 正在等待未完成的任务....
make[1]: *** [launchers-only] Error 2
make[2]: 离开目录“/home/googlewell/dragonwell8/jdk/make”
BuildJdk.gmk:75: recipe for target 'launchers-only' failed
make[1]: 离开目录“/home/googlewell/dragonwell8/jdk/make”
/home/googlewell/dragonwell8//make/Main.gmk:116: recipe for target 'jdk-only' failed
make: *** [jdk-only] Error 2
make.sh: 87: make.sh: Syntax error: "(" unexpected

**Comment by yuleil** [comment]
请提供下编译所使用的命令

**Comment by googleweb** [comment]
sh make.sh release --with-boot-jdk=/home/googlewell/jdk8u262-b10/
用的jdk是github上下载的dragonwell8的

**Comment by googleweb** [comment]
单独运行make

googlewell@jdk:~/dragonwell8$ make
Building OpenJDK for target 'default' in configuration 'linux-x86_64-normal-server-release'

## Starting langtools
## Finished langtools (build time 00:00:00)

## Starting hotspot
## Finished hotspot (build time 00:00:00)

## Starting corba
## Finished corba (build time 00:00:00)

## Starting jaxp
## Finished jaxp (build time 00:00:00)

## Starting jaxws
## Finished jaxws (build time 00:00:00)

## Starting jdk
/usr/bin/ld: warning: unrecognized --build-id style ignored.
/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o：在函数‘jar::deflate_bytes(bytes&, bytes&)’中：
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:466：对‘deflateInit2_’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:509：对‘deflate’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:516：对‘deflateEnd’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:504：对‘deflate’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:520：对‘deflateEnd’未定义的引用
/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o：在函数‘jar::addJarEntry(char const*, bool, int, bytes&, bytes&)’中：
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:61：对‘crc32’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:61：对‘crc32’未定义的引用
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:61：对‘crc32’未定义的引用
/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o：在函数‘gunzip::free()’中：
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:647：对‘inflateEnd’未定义的引用
/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o：在函数‘read_input_via_gzip(unpacker*, void*, long, long)’中：
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:550：对‘inflate’未定义的引用
/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/zip.o：在函数‘gunzip::start(int)’中：
/home/googlewell/dragonwell8/jdk/src/share/native/com/sun/java/util/jar/pack/zip.cpp:639：对‘inflateInit2_’未定义的引用
collect2: error: ld returned 1 exit status
CompileLaunchers.gmk:489: recipe for target '/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/unpack200' failed
make[2]: *** [/home/googlewell/dragonwell8/build/linux-x86_64-normal-server-release/jdk/objs/unpackexe/unpack200] Error 1
BuildJdk.gmk:75: recipe for target 'launchers-only' failed
make[1]: *** [launchers-only] Error 2
/home/googlewell/dragonwell8//make/Main.gmk:116: recipe for target 'jdk-only' failed
make: *** [jdk-only] Error 2

**Comment by luchsh** [comment]
删掉这一行 https://github.com/alibaba/dragonwell8/blob/master/make.sh#L79 中的`--with-zlib=system`，然后重新编译一下试试？

**Comment by googleweb** [comment]
谢谢，成功了，编译通过了，编译出的java运行其他程序也正常了。
那行删掉了，修改后
 --with-debug-level=$DEBUG_LEVEL $*


有点小错误，不影响了。

-------------------------
Finished building OpenJDK for target 'images'
make.sh: 86: make.sh: Syntax error: "(" unexpected

**Comment by luchsh** [comment]
也许Dragonwell不应该依赖于系统的zlib，应该使用jdk source中自带的那个， @yuleil 你觉得呢？
