### ISSUE TITLE
请问咱们是一个封闭的社区么 钉钉群二维码能不能发下

### ISSUE THREAD

**Issue by woshihoujinxin** [alibaba/dragonwell8#137]
**Description**

**Steps to Reproduce**
1. Save below snippet '...'
2. Compile it with javac '....'
3. Execute with VM options '....'

**Expected behavior**

**JDK version**
The output of `java -version` command

**Execution environment**
 - OS and version:
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by yuleil** [comment]
https://github.com/alibaba/dragonwell8/wiki/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Dragonwell8%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97

二维码可以在用户指南里找到

**Comment by woshihoujinxin** [comment]
![image](https://user-images.githubusercontent.com/3643467/95706995-eca21f00-0c8a-11eb-95b1-659e8c13244c.png)
图看不了 翻墙也不行 @yuleil

**Comment by woshihoujinxin** [comment]
可以了，可能公司把github墙了

**Comment by luchsh** [comment]
请问我能建议下你这个标题不合适吗？
每个社区都有自己的圈子和文化，你是想让那么多人去主动融入你呢，还是想融入那么多人的圈子呢？
<img width="885" alt="截屏2020-10-20 上午9 52 12" src="https://user-images.githubusercontent.com/1205973/96530429-fdb9e400-12b9-11eb-9d04-2163a91fdf1a.png">
