### ISSUE TITLE
关于dragonwell8的开发环境搭建问题？

### ISSUE THREAD

**Issue by woshihoujinxin** [alibaba/dragonwell8#138]
网络上关于如何开发jdk的文章很少，如何搭建开发jdk开发环境的教程也基本没有，这给想要入手jdk开发的同学创造了不小的学习门槛，希望社区能提供一个开发环境搭建的教程，能够演示开发过程，让更多的人参与到JDK的学习或者开发当中来。比如，用什么IDE，IDE如何配置，怎么调试源码等等。

**Comment by luchsh** [comment]
你说的这些东东非常私人化，每个开发者偏好不同，众口难调。

请问你有试过去搜索相关关键词吗？中文和英文的，不要用百度。

JDK软件本来就不是指望着每个Java开发者都能参与进去的，叶公好龙的太多，想入坑的总会找到门路，与其这里提问不如自己从源码自带的文档和OpenJDK wiki看起吧。

**Comment by joeyleeeeeee97** [comment]
目前dragonwell 使用的是adoptopenjdk 提供的一套构建测试脚本， 可以参考
https://github.com/AdoptOpenJDK/openjdk-build

**Comment by luchsh** [comment]
> 目前dragonwell 使用的是adoptopenjdk 提供的一套构建测试脚本， 可以参考
> https://github.com/AdoptOpenJDK/openjdk-build

这个对于本地开发太复杂了吧 [捂脸]
