### ISSUE TITLE
[Bug] dragonwell-8.5.4 does not ship a Windows build

### ISSUE THREAD

**Issue by luchsh** [alibaba/dragonwell8#141]
**Description**
I noticed [dragonwell-8.5.4](https://github.com/alibaba/dragonwell8/releases/tag/dragonwell-8.5.4_jdk8u272-ga) was released last Friday (good job!) but did not see a Windows build as before.

Is it the official decision that Dragonwell will cease supporting platforms other than Linux_x64?

Personally, I'll expect an open-source project to stop supporting certain platforms only when the platform itself dies, such as MacOS_PPC.
This release looks like a surprise to me, hope everything is still OK.

**Steps to Reproduce**
1. Save below snippet '...'
2. Compile it with javac '....'
3. Execute with VM options '....'

**Expected behavior**
Keep releasing Windows build as before.

**JDK version**
`8.5.4 GA`

**Execution environment**
 - OS and version: Linux
 - CPU model: x86_64
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by ziyilin** [comment]
Dragonwell8.5.4 is a release to catch up with AdoptJDK's release pace, so not all platforms are supported. A full platform supported release is under preparing now, and will be published soon.

**Comment by sanhong** [comment]
Thanks for raising this issue , the window build for  8.5.4 will come soon

**Comment by luchsh** [comment]
Does 8.5.4 contain any feature or bugfix patches from Alibaba?

**Comment by sanhong** [comment]
> Does 8.5.4 contain any feature or bugfix patches from Alibaba?

None from Alibaba, we just rebase it on latest OpenJDK 8u version.

**Comment by luchsh** [comment]
Got it, I'm closing this issue now, looking forward to the next release of Dragonwell  :)
