### ISSUE TITLE
[Misc] Fail to compile on maxOs & windows platform

### ISSUE THREAD

**Issue by joeyleeeeeee97** [alibaba/dragonwell8#142]
**Description**
Wisp Provides pseudo interfaces for macOS & windows, however in 3d30909918ed0b16925dd025c780ee87f6ef2604 introduced a new function for these two platforms missed.
![image](https://user-images.githubusercontent.com/30545334/99222170-f46e5980-281c-11eb-8a08-9ba1b1b3e425.png)

**Steps to Reproduce**
ci.dragonwell-jdk.io/view/build_scripts/job/build-scripts/job

**Expected behavior**

**JDK version**
8.5.4

**Execution environment**
 - OS and version: windows & macOs
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by luchsh** [comment]
This is exactly the problem I was worrying about, things may break if you do not keep building them.

@joeyleeeeeee97  but version `dragonwell version 8.4.5` ??? I do not see such a version from release page of dragonwell, did you mean `8.5.4`????

**Comment by joeyleeeeeee97** [comment]
> This is exactly the problem I was worrying about, things may break if you do not keep building them.
> 
> @joeyleeeeeee97 but `dragonwell version 8.4.5` ??? I do not see such a version from release page of dragonwell, did you mean `8.5.4`????

Yes. That's a typo.
To avoid this kind of issue in the future I think we need to add nightly or pull-request build for all platforms. And use a single pipeline to trigger them all.

**Comment by luchsh** [comment]
> > This is exactly the problem I was worrying about, things may break if you do not keep building them.
> > @joeyleeeeeee97 but `dragonwell version 8.4.5` ??? I do not see such a version from release page of dragonwell, did you mean `8.5.4`????
> 
> Yes. That's a typo.
> To avoid this kind of issue in the future I think we need to add nightly or pull-request build for all platforms. And use a single pipeline to trigger them all.

There has already been a pull-request build step, maybe you guys can add more platforms to it?

**Comment by joeyleeeeeee97** [comment]
> a pull-request build step, maybe you guys can add more platfom

Yes. Great advice. I found 'github action' could do this in a few lines.
