### ISSUE TITLE
[Bug] Missing testing on adopt-openjdk infra

### ISSUE THREAD

**Issue by luchsh** [alibaba/dragonwell8#145]
**Description**
I heard the Dragonwell project has now moved to [adopt-openjdk infrastructure](https://ci.adoptopenjdk.net/), which is **awesome** for outsiders and potential users.
But after glancing at the jobs of Dragonwell, I found some testing might be missing from that website, please help to take a look or correct me if I was wrong.

I was looking at [Dragonwell job on Linux x64](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-dragonwell/)

1. **First of all, one important question:** 
> Besides Github actions for each pull request, are adopt-openjdk jobs the only CI/CD process to release Dragonwell JDK?

Does Alibaba still keep private infra to do extensive testing? (of course you may choose not to disclose this for proprietary reasons.)

2. **The testing time of the following sub-jobs look too short.**
- sanity.system
- extended.system

you may compare the time with [Correto's job](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-corretto/)
Correto's time:
<img width="1222" alt="Screen Shot 2020-11-24 at 16 32 03" src="https://user-images.githubusercontent.com/1205973/100069345-9cb29c80-2e73-11eb-8a8e-88baca42495f.png">
 Dragonwell's time:
<img width="1214" alt="Screen Shot 2020-11-24 at 16 31 23" src="https://user-images.githubusercontent.com/1205973/100069359-a0462380-2e73-11eb-8186-4b96b839d5fc.png">
you may find the detailed error [here](https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk8u/job/jdk8u-linux-x64-dragonwell/84/execution/node/160/log/)

3. **Where is the testing job for unique features**
Dragonwell ships a lot of unique features, such as MultiTenant, Wisp, which do not exists in standard JDK distribution and of course are attractive, but I do not see the testing jobs listed on the adopt-openjdk website.

Will they be tested regularly and publicly?

**Steps to Reproduce**
checkout the Dragonwell jobs on  [adopt-openjdk infrastructure](https://ci.adoptopenjdk.net/)

**Expected behavior**

**JDK version**
8.5.4

**Execution environment**
 - OS and version: Linux
 - CPU model: x64
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by joeyleeeeeee97** [comment]
1. We're using adopt-openjdk pipelines both on https://ci.adoptopenjdk.net/  and http://ci.dragonwell-jdk.io/. For feature customized tests we planning to add these to sanity.openjdk test(http://ci.dragonwell-jdk.io/job/Test_openjdk11_dragonwell_sanity.openjdk_x86-64_windows/). But for now, these pipelines don't contain any tests specific for dragonwell. 

For a dragonwell release,  we verified all test pipelines locally and then we trigger from AdoptOpenJDK jenkins, hopefully would install our builds directly into AdoptOpenJDK website. (We are planing to achieve this by this release).

2. Thanks for noticing. The upstream test pipelines seem to be lost. I would check with AdoptOpenJDK community to verify this.

3. Unique features are not added to upstream pipelines yet, so our features aren't verified publicly yet.  There are some wisp nightly tests like http://ci.dragonwell-jdk.io/job/benchmarks.middleware.sae.wisp/ or  http://ci.dragonwell-jdk.io/job/test.perf.dragonwell.FrameWorkBenchmark/. Now we need to extend and make sure all features are covered.

**Comment by luchsh** [comment]
> 1. We're using adopt-openjdk pipelines both on https://ci.adoptopenjdk.net/  and http://ci.dragonwell-jdk.io/. For feature customized tests we planning to add these to sanity.openjdk test(http://ci.dragonwell-jdk.io/job/Test_openjdk11_dragonwell_sanity.openjdk_x86-64_windows/). But for now, these pipelines don't contain any tests specific for dragonwell.
> 
> For a dragonwell release, we verified all test pipelines locally and then we trigger from AdoptOpenJDK jenkins, hopefully would install our builds directly into AdoptOpenJDK website. (We are planing to achieve this by this release).
> 
> 1. Thanks for noticing. The upstream test pipelines seem to be lost. I would check with AdoptOpenJDK community to verify this.
> 2. Unique features are not added to upstream pipelines yet, so our features aren't verified publicly yet.  There are some wisp nightly tests like http://ci.dragonwell-jdk.io/job/benchmarks.middleware.sae.wisp/ or  http://ci.dragonwell-jdk.io/job/test.perf.dragonwell.FrameWorkBenchmark/. Now we need to extend and make sure all features are covered.

It sounds like you have got a solid plan, guess we may close this issue once all the 3 are fixed, right?
