### ISSUE TITLE
[Question] Which IDE is recommended to develop dragonwell8 ？ 

### ISSUE THREAD

**Issue by lovepoem** [alibaba/dragonwell8#15]
I have some questions ：

1. Which IDE is recommended to develop dragonwell8  ？ 
     IDEA or  vim ？
2. Now using GitHub as  version control tool, do we need a .gitignore file?

**Comment by luchsh** [comment]
My personal opinions:
1, pls choose whatever tool you'd like to use, there seems no official recommendations.
I've seen vim, emacs, idea, eclipse, vs code, etc. from the desktop of Alibaba JVM developers.
2, still based on your personal preferences.
take my Linux box as an example, I'm using exvim extensions on it and always add *.exvim to my local .gitignore, but I guess that may not apply to most others.

**Comment by lovepoem** [comment]
Get it , Thank you very much.
