### ISSUE TITLE
Checksum at latest release is incorrect for Windows

### ISSUE THREAD

**Issue by se35710** [alibaba/dragonwell8#156]
Ref: https://github.com/alibaba/dragonwell8/releases/tag/dragonwell-8.5.5_jdk8u275-ga

URL: https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.5.5_jdk8u275-ga/Alibaba_Dragonwell_8.5.5-Experimental_Windows_x64.zip
Expected: `25cc0788be4c9aa0e3e37ca0a9126afe9978690e339dcbb286433f7d211960e6`
Actual: `1b7dfee90585c55cf1c6ce2f7229ad9da05e86c15d94aa687f2f789ad4364dad`

**Comment by ziyilin** [comment]
Thank you for reporting this. We have it fixed.
