### ISSUE TITLE
Jwarmup unittests failed

### ISSUE THREAD

**Issue by mdianjun** [alibaba/dragonwell8#16]

**Comment by mdianjun** [comment]
I rebuild jdk images and run the unittest again, all tests are passed, please close this issue.

**Comment by kuaiwei** [comment]
I checked the test case and found a mistake in code.
` 
if (classList[i].equals(classAName)) {
     orderA = i;
     stateA = stateList[1];
}
`
The index is hard coded as 1. I will fix it.

**Comment by kuaiwei** [comment]
The attached error jtr
>
#Test Results (version 2)
#Mon Mar 25 14:02:14 CST 2019
#-----testdescription-----
$file=/export/servers/jd-jvm-8u/hotspot/test/jwarmup/TestClassInitChain.java
$root=/export/servers/jd-jvm-8u/hotspot/test
keywords=othervm
library=/testlibrary /testlibrary/whitebox
run=USER_SPECIFIED build TestClassInitChain\nUSER_SPECIFIED main ClassFileInstaller sun.hotspot.WhiteBox\nUSER_SPECIFIED main/othervm TestClassInitChain\n
source=TestClassInitChain.java
title=test ClassInitChain structure

#-----environment-----

#-----testresult-----
description=file\:/export/servers/jd-jvm-8u/hotspot/test/jwarmup/TestClassInitChain.java
elapsed=20601 0\:00\:20.601
end=Mon Mar 25 14\:02\:14 CST 2019
environment=regtest
execStatus=Failed. Execution failed\: `main' threw exception\: java.lang.RuntimeException\: 'Test Class Init Chain OK' missing from stdout/stderr
harnessLoaderMode=Classpath Loader
harnessVariety=Full Bundle
hostname=A01-R03-I182-99-BF68G42.JD.LOCAL
javatestOS=Linux 2.6.32-431.29.2.el6.x86_64 (amd64)
javatestVersion=6.0
jtregVersion=jtreg 4.2 dev 517
script=com.sun.javatest.regtest.exec.RegressionScript
sections=script_messages build build main build main
start=Mon Mar 25 14\:01\:53 CST 2019
test=jwarmup/TestClassInitChain.java
testJDK=/export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image
totalTime=20603
user.name=root
work=/export/servers/jd-jvm-8u/JTwork/jwarmup

#section:script_messages
----------messages:(10/658)----------
JDK under test: /export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image
openjdk version "1.8.0-internal"
OpenJDK Runtime Environment (build 1.8.0-internal-root_2019_03_07_17_01-b00)
OpenJDK 64-Bit Server VM (build 25.71-b00, mixed mode)
Library /testlibrary; kind: packages
   source directory: /export/servers/jd-jvm-8u/hotspot/test/testlibrary
   class directory: /export/servers/jd-jvm-8u/JTwork/classes/testlibrary
Library /testlibrary/whitebox; kind: packages
   source directory: /export/servers/jd-jvm-8u/hotspot/test/testlibrary/whitebox
   class directory: /export/servers/jd-jvm-8u/JTwork/classes/testlibrary/whitebox

#section:build
----------messages:(3/123)----------
command: build TestClassInitChain
reason: User specified action: run build TestClassInitChain 
elapsed time (seconds): 0.0
result: Passed. All files up to date

#section:build
----------messages:(3/101)----------
command: build ClassFileInstaller
reason: Named class compiled on demand
elapsed time (seconds): 0.0
result: Passed. All files up to date

#section:main
----------messages:(4/179)----------
command: main ClassFileInstaller sun.hotspot.WhiteBox
reason: User specified action: run main ClassFileInstaller sun.hotspot.WhiteBox 
Mode: othervm
elapsed time (seconds): 0.126
----------configuration:(0/0)----------
----------System.out:(0/0)----------
----------System.err:(1/15)----------
STATUS:Passed.
----------rerun:(19/1798)*----------
cd /export/servers/jd-jvm-8u/JTwork/scratch && \\
HOME=/root \\
JTREG_HOME=/export/servers/jtreg \\
LANG=en_US.UTF-8 \\
PATH=/bin:/usr/bin \\
CLASSPATH=/export/servers/jd-jvm-8u/JTwork/classes/jwarmup:/export/servers/jd-jvm-8u/hotspot/test/jwarmup:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary:/export/servers/jd-jvm-8u/hotspot/test/testlibrary:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary/whitebox:/export/servers/jd-jvm-8u/hotspot/test/testlibrary/whitebox:/export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image/lib/tools.jar:/export/servers/jtreg/lib/javatest.jar:/export/servers/jtreg/lib/jtreg.jar \\
    /export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java \\
        -Dtest.src=/export/servers/jd-jvm-8u/hotspot/test/jwarmup \\
        -Dtest.src.path=/export/servers/jd-jvm-8u/hotspot/test/jwarmup:/export/servers/jd-jvm-8u/hotspot/test/testlibrary:/export/servers/jd-jvm-8u/hotspot/test/testlibrary/whitebox \\
        -Dtest.classes=/export/servers/jd-jvm-8u/JTwork/classes/jwarmup \\
        -Dtest.class.path=/export/servers/jd-jvm-8u/JTwork/classes/jwarmup:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary/whitebox \\
        -Dtest.vm.opts= \\
        -Dtest.tool.vm.opts= \\
        -Dtest.compiler.opts= \\
        -Dtest.java.opts= \\
        -Dtest.jdk=/export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image \\
        -Dcompile.jdk=/export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image \\
        -Dtest.timeout.factor=1.0 \\
        com.sun.javatest.regtest.agent.MainWrapper /export/servers/jd-jvm-8u/JTwork/jwarmup/TestClassInitChain.d/main.0.jta sun.hotspot.WhiteBox
result: Passed. Execution successful

#section:build
----------messages:(3/101)----------
command: build TestClassInitChain
reason: Named class compiled on demand
elapsed time (seconds): 0.0
result: Passed. All files up to date

#section:main
----------messages:(4/167)----------
command: main TestClassInitChain
reason: User specified action: run main/othervm TestClassInitChain 
Mode: othervm [/othervm specified]
elapsed time (seconds): 20.472
----------configuration:(0/0)----------
----------System.out:(19/1893)----------
/export/servers/jd-jvm-8u/JTwork/scratch

Command line: [/export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java -XX:-TieredCompilation -Xbootclasspath/a:. -XX:+CompilationWarmUpRecording -XX:-ClassUnloading -XX:+UseConcMarkSweepGC -XX:-CMSClassUnloadingEnabled -XX:-UseSharedSpaces -XX:CompilationWarmUpLogfile=./jitwarmup.log -XX:CompilationWarmUpRecordTime=15 -XX:CompilationWarmUpAppID=123 -XX:+PrintCompilationWarmUpDetail -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -cp /export/servers/jd-jvm-8u/JTwork/classes/jwarmup:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary/whitebox TestClassInitChain$InnerA collection ]
[JitWarmUp] begin to collect, log file is ./jitwarmup.log
InnerA initialize
InnerB initialize
b isTestClassInitChain$InnerB@2a139a55
[JitWarmUp] output profile info has done, file is ./jitwarmup.log
process is done!

Command line: [/export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java -XX:-TieredCompilation -Xbootclasspath/a:. -XX:-UseSharedSpaces -XX:+CompilationWarmUp -XX:CompilationWarmUpLogfile=./jitwarmup.log -XX:+PrintCompilationWarmUpDetail -XX:CompilationWarmUpAppID=123 -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -cp /export/servers/jd-jvm-8u/JTwork/classes/jwarmup:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary/whitebox TestClassInitChain$InnerA compilation ]
InnerA initialize
class list length is 303
Exception in thread "main" java.lang.RuntimeException: Expected value to be true
	at com.oracle.java.testlibrary.Asserts.error(Asserts.java:468)
	at com.oracle.java.testlibrary.Asserts.assertTrue(Asserts.java:377)
	at com.oracle.java.testlibrary.Asserts.assertTrue(Asserts.java:365)
	at TestClassInitChain$InnerA.main(TestClassInitChain.java:184)

----------System.err:(27/1356)----------
 stdout: [InnerA initialize
class list length is 303
];
 stderr: [Exception in thread "main" java.lang.RuntimeException: Expected value to be true
	at com.oracle.java.testlibrary.Asserts.error(Asserts.java:468)
	at com.oracle.java.testlibrary.Asserts.assertTrue(Asserts.java:377)
	at com.oracle.java.testlibrary.Asserts.assertTrue(Asserts.java:365)
	at TestClassInitChain$InnerA.main(TestClassInitChain.java:184)
]
 exitValue = 1

java.lang.RuntimeException: 'Test Class Init Chain OK' missing from stdout/stderr 

	at com.oracle.java.testlibrary.OutputAnalyzer.shouldContain(OutputAnalyzer.java:134)
	at TestClassInitChain.main(TestClassInitChain.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:748)

JavaTest Message: Test threw exception: java.lang.RuntimeException: 'Test Class Init Chain OK' missing from stdout/stderr 

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: 'Test Class Init Chain OK' missing from stdout/stderr
----------rerun:(19/1777)*----------
cd /export/servers/jd-jvm-8u/JTwork/scratch && \\
HOME=/root \\
JTREG_HOME=/export/servers/jtreg \\
LANG=en_US.UTF-8 \\
PATH=/bin:/usr/bin \\
CLASSPATH=/export/servers/jd-jvm-8u/JTwork/classes/jwarmup:/export/servers/jd-jvm-8u/hotspot/test/jwarmup:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary:/export/servers/jd-jvm-8u/hotspot/test/testlibrary:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary/whitebox:/export/servers/jd-jvm-8u/hotspot/test/testlibrary/whitebox:/export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image/lib/tools.jar:/export/servers/jtreg/lib/javatest.jar:/export/servers/jtreg/lib/jtreg.jar \\
    /export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image/bin/java \\
        -Dtest.src=/export/servers/jd-jvm-8u/hotspot/test/jwarmup \\
        -Dtest.src.path=/export/servers/jd-jvm-8u/hotspot/test/jwarmup:/export/servers/jd-jvm-8u/hotspot/test/testlibrary:/export/servers/jd-jvm-8u/hotspot/test/testlibrary/whitebox \\
        -Dtest.classes=/export/servers/jd-jvm-8u/JTwork/classes/jwarmup \\
        -Dtest.class.path=/export/servers/jd-jvm-8u/JTwork/classes/jwarmup:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary:/export/servers/jd-jvm-8u/JTwork/classes/testlibrary/whitebox \\
        -Dtest.vm.opts= \\
        -Dtest.tool.vm.opts= \\
        -Dtest.compiler.opts= \\
        -Dtest.java.opts= \\
        -Dtest.jdk=/export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image \\
        -Dcompile.jdk=/export/servers/jd-jvm-8u/build/linux-x86_64-normal-server-release/images/j2sdk-image \\
        -Dtest.timeout.factor=1.0 \\
        com.sun.javatest.regtest.agent.MainWrapper /export/servers/jd-jvm-8u/JTwork/jwarmup/TestClassInitChain.d/main.1.jta
result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Test Class Init Chain OK' missing from stdout/stderr


test result: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: 'Test Class Init Chain OK' missing from stdout/stderr
