### ISSUE TITLE
[suggest] Submit to sdkman

### ISSUE THREAD

**Issue by tonycody** [alibaba/dragonwell8#161]
It is recommended to submit to SDKMan like other JDK releases for easy download and use.

Submission method
https://sdkman.io/vendors

SDKMan already includes the following JDKs:
AdoptOpenJDK
Amazon
Azul Zulu
BellSoft
GraalVM
TravaOpenJDK
OpenJDK

Looking forward to JDK from China.
In addition, it is recommended to submit to the IDEA JDK list so that development tools can be downloaded from China JDK

**Comment by joeyleeeeeee97** [comment]
@tonycody  Great suggestion! We plan to do this automatically with AdoptOpenJDK. 
As https://github.com/sdkman/sdkman-db-migrations/pull/419 did.

Thanks for your attention.

**Comment by tonycody** [comment]
![image](https://user-images.githubusercontent.com/6773121/107745727-b2877d80-6d4f-11eb-921f-b97d323fd050.png)
开心，终于看到中国 JDK 的身影了。
但是，冒似还是有点问题。
https://sdkman.io/jdks
这个官网里面为什么没有？

**Comment by tonycody** [comment]
@joeyleeeeeee97 老哥，感觉 sdkman 里面 dragonwell 要调整一下。不太规范。
![image](https://github.com/dragonwell-project/dragonwell8/assets/6773121/34ce0f73-2fd2-4b30-bf7a-89374a1c37f8)
Vendor 是供应商的意思，我感觉这边叫 alibaba 更合理一些。
dist 和 identifier 后面使用 drag 之类的合适些。

假如，未来阿里产生一种新的 jdk。那么这边要怎么去命名了？

可以参考一下，腾讯 Kona 的命名。我就说感觉有点怪怪的。

```shell
 Dragonwell    |     | 17.0.8       | albba   |            | 17.0.8-albba
               |     | 17.0.7       | albba   |            | 17.0.7-albba
               |     | 11.0.20      | albba   |            | 11.0.20-albba
               |     | 11.0.19      | albba   |            | 11.0.19-albba
               |     | 8.0.382      | albba   |            | 8.0.382-albba
               |     | 8.0.372      | albba   |            | 8.0.372-albba
               |     | 8.0.275      | albba   |            | 8.0.275-albba

 Tencent       |     | 17.0.9       | kona    |            | 17.0.9-kona
               |     | 17.0.8       | kona    |            | 17.0.8-kona
               |     | 17.0.7       | kona    |            | 17.0.7-kona
               |     | 11.0.21      | kona    |            | 11.0.21-kona
               |     | 11.0.20      | kona    |            | 11.0.20-kona
               |     | 11.0.19      | kona    |            | 11.0.19-kona
               |     | 8.0.392      | kona    |            | 8.0.392-kona
               |     | 8.0.382      | kona    |            | 8.0.382-kona
               |     | 8.0.372      | kona    |            | 8.0.372-kona
```

**Comment by joeyleeeeeee97** [comment]
@tonycody albba确实有点奇怪。

如果要修改缩写的话可以改下这里
https://github.com/sdkman/sdkman-disco-integration/blob/ccf40ad82ab3392b52425d9daa62e31144bf16c3/src/main/java/io/sdkman/automigration/adapters/PackageAdapter.java#L24  

cc: @Accelerator1996

**Comment by tonycody** [comment]
> @tonycody albba确实有点奇怪。
> 
> 如果要修改缩写的话可以改下这里 https://github.com/sdkman/sdkman-disco-integration/blob/ccf40ad82ab3392b52425d9daa62e31144bf16c3/src/main/java/io/sdkman/automigration/adapters/PackageAdapter.java#L24
> 
> cc: @Accelerator1996

我理解应该和腾讯一样，Vendor 是企业名称：Alibaba
Alibaba    |     | 17.0.8       | dragonwell   |            | 17.0.8-dragonwell

我感觉这样合理些！

**Comment by tonycody** [comment]
@joeyleeeeeee97 @Accelerator1996 简单了解一下，要改变 SDKMan 上 Vendor 标识信息不是那么简单。对应的包要重新提交到  Foojay´s Disco。

**Comment by Accelerator1996** [comment]
> @joeyleeeeeee97 @Accelerator1996 简单了解一下，要改变 SDKMan 上 Vendor 标识信息不是那么简单。对应的包要重新提交到 Foojay´s Disco。

@tonycody 是的，我们会关注这个问题的，非常感谢反馈
