### ISSUE TITLE
我要怎么获取源码？

### ISSUE THREAD

**Issue by binaryCodeSequence** [alibaba/dragonwell8#188]
我要怎么获取源码？

**Comment by zhangruoxu** [comment]
Hi,
Alibaba Dragonwell 8 follows upstream, where different components of JDK are maintained in different repos. You could check the shell script

https://github.com/alibaba/dragonwell8/blob/master/get_source_dragonwell.sh

to find the location of each component. For example, you could find the source code of HotSpot in the repo

https://github.com/alibaba/dragonwell8_hotspot

Happy coding :-)

Cheers,
Yifei
