### ISSUE TITLE
运行了一段时间时间应用直接挂掉

### ISSUE THREAD

**Issue by clivhua** [alibaba/dragonwell8#189]
A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fdf31f2749f, pid=61205, tid=0x00007fdea5d56700
#
# JRE version: OpenJDK Runtime Environment (8.0_275) (build 1.8.0_275-_2020_12_15_09_29-b00)
# Java VM: OpenJDK 64-Bit Server VM (25.275-b00 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x6bf49f]  java_lang_Thread::get_thread_status(oopDesc*)+0xf
[hs_err_pid65.log](https://github.com/alibaba/dragonwell8/files/5864989/hs_err_pid65.log)
目前使用到版本：Alibaba_Dragonwell_8.5.5-GA_Linux_x64

**Comment by zhengxiaolinX** [comment]
Thank you for opening this issue.
We cannot reproduce this issue in our local environment. Could you please provide more information about this crash?
1. environment: your application type, based on spring-boot / jetty etc.
2. frequency of reproducing this problem
3. if it's reproducible, could version 8.4.4 generates the same problem?
4. better to offer us a case to reproduce this problem
Thank you for your help!

**Comment by clivhua** [comment]
tomcat9.0.39发生crash,生了一次，目前更新tomcat到9.0.41版在使用。 生产系统涉及比较多，不容抽离故障代码case。

**Comment by luchsh** [comment]
我稍微喵了一眼日志，一些线索是：
- 看起来执行的指令是`move (rdi, rax, 1), rax`
- rax=0x30看起来没啥问题
- rdi=0x79bfa9970是合法的heap地址`[0x0000000700000000~ 0x00000007C0000000]`；
- 但日志中`RDI=0x000000079bfa9970 is an unallocated location in the heap`，所以是不是rdi所代表的c++层存储的某些oop值在GC的时候没有更新或假如GC root？

**Comment by zhengxiaolinX** [comment]
实在是非常有启发性的提醒，"an unallocated location in the heap" 的确不太正常。我多加几个 guarantee 排查一下。

**Comment by zhengxiaolinX** [comment]
> 我稍微喵了一眼日志，一些线索是：
> 
> * 看起来执行的指令是`move (rdi, rax, 1), rax`
> * rax=0x30看起来没啥问题
> * rdi=0x79bfa9970是合法的heap地址`[0x0000000700000000~ 0x00000007C0000000]`；
> * 但日志中`RDI=0x000000079bfa9970 is an unallocated location in the heap`，所以是不是rdi所代表的某些 **协程** c++层存储的oop在GC的时候没有更新或没加入GC root？

我只能说胜哥无敌

**Comment by zhengxiaolinX** [comment]
这个问题在接下来的 Dragonwell 8.12.13 中理论上是修复掉了，所以我先关闭这个 issue 了。如果之后还有问题的话请随时 reopen。
