### ISSUE TITLE
Two suggestions for building scripts

### ISSUE THREAD

**Issue by shanlaomao** [alibaba/dragonwell8#20]
1. The following error occurred when executing the `get_source_dragonwell.sh -s github` command

```
Cloning into 'dragonwell8-corba'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I know this because I didn't set GitHub SSH public key.
It is suggested that line 66 of get_source_dragonwell.sh be changed from `GITURL= "git@github.com:alibaba"` to `GITURL= "https://github.com/alibaba"`. 
This problem can be solved simply and effectively.

2. It is suggested to add executable permissions to the `configure` script.

**Comment by luchsh** [comment]
Thank you for the suggestion, will fix.

**Comment by luchsh** [comment]
The first suggestion has been covered by following fix:
https://github.com/alibaba/dragonwell8/commit/22dbbb37b35f24b999b9045bfc6cfec74965a58a

Fort the second, Dragonwell was trying to be consistent with OpenJDK, see http://hg.openjdk.java.net/jdk/jdk/file/55c4283a7606/configure

I'm closing this issue based on the above observations, please reopen if you feel necessary.
Cheers
