### ISSUE TITLE
Add ECMAScript6 support in Nashorn

### ISSUE THREAD

**Issue by rockswang** [alibaba/dragonwell8#21]
The javascript engine, aka. nashorn in Java8 is ES5 based, ES6 support was added in Java9.
Hope dragonwell can add support of ES6 language features.

**Comment by luchsh** [comment]
I'm afraid this change may break compatibility with OpenJDK8, Dragonwell8 should avoid that.
Maybe in future LTS releases, like Dragonwell-11, this can be supported :)
