### ISSUE TITLE
线上使用龙井jdk对比测试，服务AVG以及99线耗时都有降低，性能提升明显，原因是？

### ISSUE THREAD

**Issue by addichen** [alibaba/dragonwell8#219]
**Description**
对于吞吐性能提升以及CPU使用的提升比较好理解
但是对于服务性能耗时的提升，如何解释，求指点

**Comment by joeyleeeeeee97** [comment]
@addichen  能否提供下您线上运行的jvm参数 和 环境信息?

**Comment by addichen** [comment]
/usr/local/jdk8u282-b1/bin/java -server -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Djava.io.tmpdir=/tmp -Djava.net.preferIPv6Addresses=false -Dapp.port=8978 -Dorg.eclipse.jetty.server.Request.maxFormContentSize=5000000 -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -Dio.netty.noUnsafe=true -Dio.netty.transport.noNative=true -Xmx6g -Xms6g -Xss512k -XX:MetaspaceSize=128m -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:InitiatingHeapOccupancyPercent=40 -XX:MaxGCPauseMillis=100 -XX:+TieredCompilation -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution

环境：
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.6.5) (build 1.8.0_282-b1)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.6.5) (build 25.282-b1, mixed mode)
Linux version 4.18.0-80.mt20191225.323.el8_0.x86_64 (gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)) #1 SMP Fri Jan 10 15:57:27 CST 2020
CentOS Linux release 7.6.1810 (Core)

**Comment by addichen** [comment]
/usr/local/jdk8u282-b1/bin/java -server -Dfile.encoding=UTF-8 -Dsun.jnu.encoding=UTF-8 -Djava.io.tmpdir=/tmp -Djava.net.preferIPv6Addresses=false -Dapp.port=8978 -Dorg.eclipse.jetty.server.Request.maxFormContentSize=5000000 -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -Dio.netty.noUnsafe=true -Dio.netty.transport.noNative=true -Xmx6g -Xms6g -Xss512k -XX:MetaspaceSize=128m -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:InitiatingHeapOccupancyPercent=40 -XX:MaxGCPauseMillis=100 -XX:+TieredCompilation -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution

环境：
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.6.5) (build 1.8.0_282-b1)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.6.5) (build 25.282-b1, mixed mode)
Linux version 4.18.0-80.mt20191225.323.el8_0.x86_64 (gcc version 7.3.1 20180303 (Red Hat 7.3.1-5) (GCC)) #1 SMP Fri Jan 10 15:57:27 CST 2020
CentOS Linux release 7.6.1810 (Core)

**Comment by yuleil** [comment]
您好，有两方面原因:

1. 您开启了-XX:+UseWisp2 ，这项功能是专门为提高微服务性能而生的
2. Dragonwell对一些"看不见的地方"做了优化或者backport，比如GC上的[OWST](https://bugs.openjdk.java.net/browse/JDK-8214458)优化。
