### ISSUE TITLE
how to install dragonwell using brew 

### ISSUE THREAD

**Issue by LinBoLen** [alibaba/dragonwell8#22]
expected feature:
brew tap dragonwell/dragonwell
brew install dragonwell

ls /Library/Java/JavaVirtualMachines/dragonwell-jdk
...

java -version 
...

**Comment by luchsh** [comment]
Hi LinBolen,
Dragonwell only supports Linux-x64 platforms for now.
So from my point of view, this request sounds more likely to be "Need MacOS support of Dragonwell",
 I'll leave it open until there is a solution.
Thank you!

**Comment by cuipengfei** [comment]
MacOS still not supported yet?

**Comment by luchsh** [comment]
I guess no; but I'm not working for Alibaba now, this is not an official answer.
 @yuleil  do you wanna clarify?
