### ISSUE TITLE
[aarch64] Current aarch64 support need reverting, because OpenJDK8u mainline support aarch64 since 292

### ISSUE THREAD

**Issue by sandlerwang** [alibaba/dragonwell8#228]
OpenJDK8u mainline has aarch64 support since 292, and this conflicts with current aarch64 support in Dragonwell8.
Need to revert current aarch64 support, to prepare further merge with 8u292

**Comment by joeyleeeeeee97** [comment]
@sandlerwang  Please add another patch to remove this include in common part 
![image](https://user-images.githubusercontent.com/30545334/119944919-6cd18680-bfc7-11eb-80ac-30c8761b4c7d.png)
