### ISSUE TITLE
Doesn't support windows?

### ISSUE THREAD

**Issue by cumtcwf** [alibaba/dragonwell8#23]
**Description**

**Steps to Reproduce**
1. Save below snippet '...'
2. Compile it with javac '....'
3. Execute with VM options '....'

**Expected behavior**

**JDK version**
The output of `java -version` command

**Execution environment**
 - OS and version:
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by luchsh** [comment]
For now, Drogonwell does not provide pre-built JDK for Windows.
But you may try to compile by yourself according to this document:
https://github.com/alibaba/dragonwell8/blob/master/README-builds.html
