### ISSUE TITLE
支持Docker?  是否支持 alpine 3.9？

### ISSUE THREAD

**Issue by xiaolongyuan** [alibaba/dragonwell8#24]

**Comment by terwer** [comment]
I hasve a project with docker,you can have a try
[](https://github.com/terwer/docker-dragonwell8)

**Comment by luchsh** [comment]
Please try to use the issue template.
I do not quite understand the question of "support docker?", may I ask do you mean "can it run on docker?", "does it recognize docker metrics? like this one https://bugs.openjdk.java.net/browse/JDK-8203357"

**Comment by luchsh** [comment]
@xiaolongyuan  any comments?
if no, I'll close this issue.
