### ISSUE TITLE
[Bug] A new bug

### ISSUE THREAD

**Issue by vae1970** [alibaba/dragonwell8#252]
docker file现在还可以支持alpine OS吗

**Comment by luchsh** [comment]
支持啊，请看文档：https://github.com/alibaba/dragonwell8/wiki/Use-Dragonwell8-docker-image
这种问题 Dragonwell Team 为啥没人出来回答呢？！

**Comment by vae1970** [comment]
新版的docker file都只有centos了，希望能支持一下alpine OS

**Comment by vae1970** [comment]
新版的docker file都只有centos了，希望能支持一下alpine OS
