### ISSUE TITLE
[Backport] 8225690: Multiple AttachListener threads can be created

### ISSUE THREAD

**Issue by XHao** [alibaba/dragonwell8#261]
Description：
VM can't be attached If someone clean up the /tmp directory.
[JDK-8225690 Multiple AttachListener threads can be created](https://bugs.openjdk.java.net/browse/JDK-8225690) can fix this.

**Comment by D-D-H** [comment]
Hi @XHao ,

I agree with this backport, but I think that we should discuss this backport in the OpenJDK 8u community, which will also benefit other users using JDK 8.

(The link you posted in the description is not right.)

**Comment by kelthuzadx** [comment]
I will try to backport this to OpenJDK 8u upstream and also backport to Dragonwell 8 once upstream OpenJDK 8u upstream is merged.

**Comment by kelthuzadx** [comment]
@luchsh https://mail.openjdk.java.net/pipermail/jdk8u-dev/2021-October/014316.html

**Comment by kelthuzadx** [comment]
@luchsh Sorry for confusion before. I've prepared a backport changeset to wait for approval. 

https://mail.openjdk.java.net/pipermail/jdk8u-dev/2021-October/014334.html

**Comment by D-D-H** [comment]
> Patches in upstream are merged, I'd like to backport them to downstream(dragonwell8), will get back soon.

Thanks, but I think this backport will be auto included in the next release of Alibaba dragonwell 8, we don't need to backport it again, right?

**Comment by D-D-H** [comment]
@XHao 
Hi,
This issue has been backported to OpenJDK 8u (https://bugs.openjdk.java.net/browse/JDK-8274953).
And the next Alibaba Dragonwell 8 release will include this fix.
So I close this issue and please feel free to reopen it if you need.
