### ISSUE TITLE
[Bug] Missing issue links in Release Notes

### ISSUE THREAD

**Issue by luchsh** [alibaba/dragonwell8#271]
**Description**
Since 8.6.6, issue links are missing from Release Notes, which is inconvenient to jump to the released issues.

CN: https://github.com/alibaba/dragonwell8/wiki/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Dragonwell8%E5%8F%91%E5%B8%83%E8%AF%B4%E6%98%8E
EN: https://github.com/alibaba/dragonwell8/wiki/Alibaba-Dragonwell8-Release-Notes

This is not a good signal for an open-source project, which usually implies the decay of code.

I also see 8.4.4 (a released version) on tab `Projects`， shall we close it?
https://github.com/alibaba/dragonwell8/projects

**Steps to Reproduce**

**Expected behavior**
Jump to the right issue when browsing the release notes.

**JDK version**
`>= 8.6.6 Release`

**Execution environment**
Documentation defects

**Comment by yuleil** [comment]
Thanks, will fix

**Comment by sanhong** [comment]
Thank you for the suggestions!

**Comment by yuleil** [comment]
The Issue links have been added
