### ISSUE TITLE
Request to add more `provides` for rpm package

### ISSUE THREAD

**Issue by whhe** [alibaba/dragonwell8#272]
OS: CentOS 7.9

The `Provides` of dragonwell8 rpm package are as follows:

```
[root@6395dd2c9080 home]# rpm -q --provides java-1.8.0-alibaba-dragonwell       ​
java-1.8.0-alibaba-dragonwell = 8.8.8.302.b1-1.al7
java-1.8.0-alibaba-dragonwell(x86-64) = 8.8.8.302.b1-1.al7
```

OpenJDK returns more:

```
[root@6395dd2c9080 home]# rpm -q --provides java-1.8.0-openjdk                  
application()
application(java-1.8.0-openjdk-1.8.0.312.b07-1.el7_9.x86_64-policytool.desktop)
java = 1:1.8.0
java-1.8.0 = 1:1.8.0.312.b07-1.el7_9
java-1.8.0-openjdk = 1:1.8.0.312.b07-1.el7_9
java-1.8.0-openjdk(x86-64) = 1:1.8.0.312.b07-1.el7_9
java-fonts = 1:1.8.0.312.b07
java-openjdk = 1:1.8.0.312.b07-1.el7_9
jre = 1.8.0
jre-1.8.0 = 1:1.8.0.312.b07-1.el7_9
jre-1.8.0-openjdk = 1:1.8.0.312.b07-1.el7_9
jre-openjdk = 1:1.8.0.312.b07-1.el7_9
```
Now I want to use jdk8 as a `Requires` item for my rpm package, and I think it would be great to set a general value for it. But now dragonwell doesn't share any `Provides` fields with OpenJDK, so I'm wondering if dragonwell can add some `Provides` that are same with OpenJDK to make it works.

**Comment by luchsh** [comment]
As I can remember the RPM scripts were maintained in a private repository within Alibaba, maybe Dragonwell can opensource that script too? @joeyleeeeeee97 

To make it easier to adopt Dragonwell, maybe folks of this community should try to release packages for mainstream Linux distributions, such as Debian, Fedora, or even Archlinux. :)

**Comment by joeyleeeeeee97** [comment]
Thank you for your feedback. 
Dragonwell 8u312 is not released yet, and for now publishing rpm to package servers is not automated.
Adding Dragonwell to default release package in popular system is a great idea, we are beginning with Alibaba Cloud Linux and OpenAnolis, and hopefully all mainstream distributions.
