### ISSUE TITLE
[JFR] Deprecate public JFR Streaming API

### ISSUE THREAD

**Issue by D-D-H** [alibaba/dragonwell8#275]
Hi,

For better maintainability and compatibility purposes, and considering that almost no users are using JFR Streaming of Alibaba Dragonwell 8, we decided to deprecate the JFR Streaming public API in 8.9.10, and revert the JFR Streaming related backport patches in the next version(three months later).

If you are currently using JFR Streaming related features, please let us know.

Denghui

**Comment by joeyleeeeeee97** [comment]
pin

**Comment by joeyleeeeeee97** [comment]
ping
