### ISSUE TITLE
[Wiki] A new bug

### ISSUE THREAD

**Issue by ShuaiJunlan** [alibaba/dragonwell8#277]
`docker pull registry.cn-hangzhou.aliyuncs.com/dragonwell/dragonwell8:dragonwell-8.8.9_jdk8u302-ga_x86_64`

Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/dragonwell/dragonwell8:dragonwell-8.8.9_jdk8u302-ga_x86_64 not found: manifest unknown: manifest unknown

The docker image not found, refer from: [https://github.com/alibaba/dragonwell8/wiki/Use-Dragonwell8-docker-image](https://github.com/alibaba/dragonwell8/wiki/Use-Dragonwell8-docker-image)

Please provide the correct urls, thanks.

**Comment by joeyleeeeeee97** [comment]
@ShuaiJunlan .
Updated. please use registry.cn-hangzhou.aliyuncs.com/dragonwell/dragonwell:dragonwell-8.8.9_jdk8u302-ga_x86_64_slim
