### ISSUE TITLE
Dead link on dragonwell-jdk-io for latest JDK 8 build for linux x86_64

### ISSUE THREAD

**Issue by HanSolo** [alibaba/dragonwell8#297]
**Description**
When selecting Dragonwell 8 with x86_64 and linux on the dragonwell-jdk.io page, 
the link shows a build for windows (https://github.com/alibaba/dragonwell8/releases/download/untagged-1b7797abe41fe9b18682/Alibaba_Dragonwell_8.9.10_x64_windows.zip).

When you click the download button it seems the link is dead.

**Steps to Reproduce**
1. Go to https://dragonwell-jdk.io/
2. Select Dragonwell 8, x86_64, linux
3. Press the download button

**Expected behavior**
Get the selected Dragonwell 8 build for linux

**JDK version**
Dragonwell 8

**Execution environment**
- Any browser

**Comment by joeyleeeeeee97** [comment]
fixed. please take another look. the latest version is 8.10.11 prerelease

**Comment by HanSolo** [comment]
Works...awesome...thx for the very quick replay 👍🏻
