### ISSUE TITLE
[Bug] A new bug with the option -XX:-UnrollLimitCheck

### ISSUE THREAD

**Issue by feixiangdejiahao** [alibaba/dragonwell8#305]
**Description**
Run arbitrary program with -XX:-UnrollLimitCheck, Dragonwell8 crashes

**Steps to Reproduce**
```
$ java -Xcomp -XX:+UnlockDiagnosticVMOptions -XX:-UnrollLimitCheck -version
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007faaa4fcd211, pid=755, tid=0x00007faa484d7700
#
# JRE version: OpenJDK Runtime Environment (8.0_322) (build 1.8.0_322-internal-user_2022_03_21_20_47-b00)
# Java VM: OpenJDK 64-Bit Server VM (25.322-b00 compiled mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x87b211]  PhaseIdealLoop::build_loop_late_post(Node*)+0x111
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
```
**Expected behavior**
openjdk version "1.8.0_322-internal"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.10.11) (build 1.8.0_322-internal-user_2022_03_21_20_47-b00)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.10.11) (build 25.322-b00, mixed mode)

**JDK version**
openjdk version "1.8.0_322-internal"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.10.11) (build 1.8.0_322-internal-user_2022_03_21_20_47-b00)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.10.11) (build 25.322-b00, mixed mode)

**Execution environment**
 - OS and version: Ubuntu 18.04
 - CPU model: Intel(R) Xeon(R) Gold 6240

**Comment by kelthuzadx** [comment]
This is possibly a known issue, see [JDK-8072422](https://bugs.openjdk.java.net/browse/JDK-8072422) for more details. You are not supposed to run with this flag switched off. It is more a develop flag then diagnostic used during feature development. We would evaluate if it's reasonable to backport the fix patch to dragonwell 8.

**Comment by feixiangdejiahao** [comment]
Thanks for your patient help! I thought that since the user should not turn the flag off at the run time and the flag is enabled in default, it might be reasonable to remove the option or move it to the debug version rather than simply requiring users not to use it in this way.
