### ISSUE TITLE
这个JDK m1芯片的可以使用么

### ISSUE THREAD

**Issue by lumengda** [alibaba/dragonwell8#306]
小白问一下，这个JDK. m1芯片的苹果电脑可以使用么，Windows呢，还是说目前只支持Linux服务器

**Comment by joeyleeeeeee97** [comment]
m1的macbook暂时不支持。
![image](https://user-images.githubusercontent.com/30545334/161938287-e1c0a08d-8c7c-450b-860a-574e2fa6ab2f.png)
