### ISSUE TITLE
Alibaba_Dragonwell_8.9.10_x86_windows.zip资源不正确

### ISSUE THREAD

**Issue by theodore26** [alibaba/dragonwell8#309]
下载[Alibaba_Dragonwell_8.9.10_x86_windows.zip](https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.9.10_jdk8u312-ga/Alibaba_Dragonwell_8.9.10_x86_windows.zip)版本。
下载后，获取版本信息，为：
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.9.10) (build 1.8.0_312-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.9.10) (build 25.312-b01, mixed mode)
比较下载后的[Alibaba_Dragonwell_8.9.10_x86_windows.zip](https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.9.10_jdk8u312-ga/Alibaba_Dragonwell_8.9.10_x86_windows.zip)和[Alibaba_Dragonwell_8.9.10_x64_windows.zip](https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.9.10_jdk8u312-ga/Alibaba_Dragonwell_8.9.10_x64_windows.zip)，校验文件SHA256都是bdc5aaaf8b1b8469ae1e8b5513db9d0a65a610c9d61cae389954f44100ac7272。
打开 [Alibaba_Dragonwell_8.9.10_x86_windows.zip.sha256.txt](https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.9.10_jdk8u312-ga/Alibaba_Dragonwell_8.9.10_x86_windows.zip.sha256.txt)，里面的内容与[Alibaba_Dragonwell_8.9.10_x64_windows.zip.sha256.txt](https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.9.10_jdk8u312-ga/Alibaba_Dragonwell_8.9.10_x64_windows.zip.sha256.txt)一致。

**Comment by joeyleeeeeee97** [comment]
hi,  请使用 https://github.com/alibaba/dragonwell8/releases/download/dragonwell-8.9.10_jdk8u312-ga/Alibaba_Dragonwell_8.9.10_x64_windows.zip 版本进行测试，目前windows不支持x86的版本。
下载到的应该也都是OpenJDK 64-Bit 的版本。
支持的详情
![image](https://user-images.githubusercontent.com/30545334/161912338-5324cdc0-186b-4391-a1de-756eb898ba84.png)
