### ISSUE TITLE
[jwarmup] -XX:-TieredCompilation即禁用C1，是否对应用造成一定程度的性能损耗？

### ISSUE THREAD

**Issue by lhh-yeah** [alibaba/dragonwell8#314]
如题 ，在回放jwarmup log阶段，jvm参数需配置-XX:-TieredCompilation（即禁用C1），是否对应用造成一定程度的性能损耗？

**Comment by lhh-yeah** [comment]
补充，这是不是意味着在record阶段要尽可能收集编译日志，包括C1编译日志；如果不在收集范围内则就只能等待C2编译，不能享受分层编译的好处了。

**Comment by kuaiwei** [comment]
JWarmup的做法是热点方法能跳过解释器和C1编译，直接进入高性能的C2编译。本身是有些取舍的，放弃了C1的快速编译，但可以更快的达到性能峰值。

**Comment by lhh-yeah** [comment]
多谢你的回复！
因为-XX:-TieredCompilation的话，codeCache的大小会比开启分层编译的codeCache缩小5倍，意味着需要适当地调节ReservedCodeCacheSize参数对吧？
另外有个问题就是dragonwell8的jwarmup record阶段的性能损耗是多少，有相关报告吗？

**Comment by lhh-yeah** [comment]
在Record阶段，会同时记录下C1和C2编译日志？
在Compile阶段，由于添加-XX:-TieredCompilation，此时会编译Record阶段的C1和C2编译日志？ 还是仅编译Record阶段记录下的C2编译日志？    如果仅编译Record阶段记录下的C2编译日志，那是不是意味着原本仅能达到C1级别的这些方法无法被JIT优化？

**Comment by lhh-yeah** [comment]
jwarmup的测试表现基本能符合预期，但在实践中仍有上述疑惑，期望等到解答，谢谢。
