### ISSUE TITLE
龙井jdk什么时候适配M1芯片

### ISSUE THREAD

**Issue by scc6868312** [alibaba/dragonwell8#315]
龙井jdk什么时候适配M1芯片?未来会适配吗

**Comment by D-D-H** [comment]
@scc6868312 
哈喽，上游支持 Mac M1 的版本为 17 （相关的 JEP 是 http://openjdk.java.net/jeps/391 ），你可以选择尝试使用 [Dragonwell 17](https://github.com/alibaba/dragonwell17) 在 Mac M1 的机器上进行构建。
