### ISSUE TITLE
garbage collection choice

### ISSUE THREAD

**Issue by duansheli** [alibaba/dragonwell8#32]
# 垃圾回收器的选择问题

在使用oracle版的jdk时， 可以参考文档对gc进行具体参数配置。
https://docs.oracle.com/javase/8/docs/technotes/guides/vm/gctuning/

那阿里的openjdk的gc参数和oracle的也是通用的吗

**Comment by luchsh** [comment]
Apologize for the delay.
Yes, the docs may also apply to Dragonwell.
But one obvious difference is about the default GC policy: OpenJDK && Oracle JDK uses 'PS(Parallel Scavenge, -XX:+UseParallelGC)', but Dragonwell uses 'CMS (Concurrent Mark Sweep, -XX:+UseConcMarkSweepGC)'.
