### ISSUE TITLE
使用预热后的文件报错告警

### ISSUE THREAD

**Issue by M-Davinci** [alibaba/dragonwell8#327]
[JitWarmUp] DEBUG : class io/netty/handler/codec/CodecOutputList$1 is not in profile
[JitWarmUp] WARNING : loaded class io/netty/handler/codec/CodecOutputList$1 at index 13427 is ignored
[JitWarmUp] DEBUG : class io/netty/handler/codec/CodecOutputList$CodecOutputLists is not in profile
[JitWarmUp] DEBUG : class org/apache/dubbo/remoting/exchange/support/MultiMessage is not in profile
[JitWarmUp] DEBUG : class org/apache/dubbo/remoting/exchange/Response is not in profile
[JitWarmUp] DEBUG : class org/apache/dubbo/common/serialize/hessian2/Hessian2ObjectInput is not in profile
[JitWarmUp] DEBUG : class com/alibaba/com/caucho/hessian/io/AbstractHessianInput is not in profile
[JitWarmUp] DEBUG : class com/alibaba/com/caucho/hessian/io/Hessian2Input is not in profile
[JitWarmUp] DEBUG : class org/apache/dubbo/remoting/Codec2$DecodeResult is not in profile

**Comment by luchsh** [comment]
忽略它怎样？毕竟咱们码农更在意ERROR嘛

**Comment by M-Davinci** [comment]
> 谢谢问题找到了

**Comment by liuzhiguo630** [comment]
> > 谢谢问题找到了

是什么问题呢？我这里也遇到这些日志，开了 jwarmup 比不开启动还慢。
