### ISSUE TITLE
Java Floating Point Arithmetic and StrictMath Method Denormal and Pronormal Error Correction.

### ISSUE THREAD

**Issue by PowerUser1234** [alibaba/dragonwell8#331]
This discussion is a continuation of

[https://github.com/alibaba/dragonwell8/issues/318](https://github.com/alibaba/dragonwell8/issues/318)

To Alibaba,

Java floating point errors occur by means of a representation issue to do with using the 
IEEE 754 floating point binary equation during arithmetic in converted binary for floating point dot separator (“decimal point”) types in Java, namely, float and double, along with incorrect implementation in method logic inside the java.lang.StrictMath class.

Floating point errors in Java do occur in the decimal and hexadecimal unit in the last place and the hexadecimal unit in the last place, to the right of the decimal point or the dot separator.  When they do occur, there is either a binary overflow or underflow.  Those results, when converted back to base 10 or 16, break the contiguous range property in a ranged base 10 and base 16 number line, at an unknown magnitude that is higher or lower than accurate.

It is impossible to understand who could possibly, in any meaningful way, need or rely on, exactly, an inconsistent and chaotic number value situation, particularly in base 10.  It is  an error and a bug situation that should be corrected by a Java language Vendor.  Some people might claim that they want approximations, noting a time reduction involved.  But more important is the need for accuracy, which can be achieved with negligible time issues involved.

Java JDK/JRE Java runtimes generate floating point arithmetic or java.lang.StrictMath denormal and pronormal values as a result of Java source code like this, either in the defaulting base 10 mode, but also when hexadecimal notation for base 16 numbers starts to be used, which is denoted with a 0x inside float and double, where the errors may occur.  These are presently all error phenomena which can and aught be fixed:

```
// The Java Language.  Arithmetic only, no comparisons.

import static java.lang.System.*;
public class Start
{
    public static void main(String ... args)
    {
    out.println("Program has started...");   
    out.println();   
    float a = 0.1F;   
    float b = 0.1F;   
    float c = a*b;   
    out.println(c);
    double d = 0.1D; 
    double e = 0.1D;
    double f = d*e;
    out.println();   
    out.println(f);
    out.println(); 
    out.println("Program has Finished.");
    }}
```

**Program has started...**

**0.010000001**

**0.010000000000000002**

**[0.01?]**

**Program has Finished.**

The standard that Java turns to for arithmetic, IEEE 754, doesn't specifically say anything about the base 10 or base 16 digit degradation via overflow or underflow that does happen at the right hand side, unit in the last place, of floating point decimal and hexadecimal number type value data with the dot separator.  The older view that floating point can be an approximation trade-off for range accuracy is not the only view involved and not a requirement; it is certainly not implied in the terms themselves, which talking about the dot separator's positioning .  There is other correct thought and implementation out there, which sees the need and respond with a digit trade-off of precisely zero (0) within an appropriately limited range, of a practical form.  

One of the primary views around numbers, arithmetic and functions in modern times is that binary is for computers, and denary is for human beings.  An approach which mixes these two up at the same time, while not maintaining separation between these concerns, only leads to logic confusion and errors.  In the OpenJDK, float and double are the main offenders of that, however a similar problem occurs with java.lang.StrictMath method calls.  Most importantly, this happens in relation to base 10, but base 16 has the same problem, within the two Java floating point types.  All examples of such are logic errors, that need to be repaired in either a default or mutual way, simply because denary accuracy is required out of a compiled and running Java program, either at its conclusion or some mid point, or from the start.  Relevant Computer hardware that the writer of this message has in mind is the Desktop PC, running any ubiquitous operating system, or as configured as a database or internet server.

Workarounds are used, being BigInteger, BigDecimal, and the big-math library and similar, in Java.  They introduce an entire tier to Java software which isn't needed to cover for floating point errors themselves, really.  BigInteger and BigDecimal are slow and produce a loss in speed, are larger in RAM and waste memory, and don't allow the use of arithmetic operator source code syntax.  To say nothing about the absence of an included accurate type calculator class.  Things that developers and their programs need.  

**Floating Point correction doesn't mean that only the default behaviour be changed.  It can be achieved compatibility.  There could be a patch program for the JRE, separate to the main Java download.  Working not to change how Java compiles, there could be a runtime switch which can be wrapped around a Java invocation by previous mode Java code.  There could be an overhead static class with methods that can be called to apply to code spaces, being all code spaces inside a main method, a Thread start method, Runnables, Futures, static blocks or any similar.  Something similar could be possible by using annotations for the runtime, if that is appropriate given efficiency concerns.  But so long as the contents of a float and a double can read and write over one another while their lines of execution are in step, both modes of operation could be used at the same time if things were set up consistently, accessibly enough.  All that is presuming that the bolder step of total default change isn't to be taken.**

The IEEE should include or state something new in its standard 754 to encourage software language vendor(s) to implement floating point arithmetic more completely for overflow and underflow concerns, but if it doesn't, vendor(s) are left to act on their own.  Oracle and the Java Community process have not apprehended repeated bug requests, and have chosen not to act further despite multiple discussion attempts about the needs involved, in their relevant public email lists.  While it would be most appropriate for the most upstream Vendor to implement these corrections, in face of a total refusal, the best remaining option is to inquire of other vendors, which is the purpose of this message.

The following is a version of the IEEE 754 floating point binary number formula in Java:

`n2=(-1)s*m2*2e2-(L-1)`

It is defined by the the sign of the number's positivity or negativity,  mantissa of the registry in binary (m2) which are the digits of the number from denary, the exponent of the registry in binary (e2) which is the position of the dot separator or decimal point, for a 32 bit or 64 bit number (float or double).  Interestingly, this can already be applied to a 128 bit number which Java doesn't support at the primitive level.

The most concomitant correction approach is to augment the present circumstances with available hardware bit registers, and more implementation logic.  That is, introducing two range limits each for float and double, values range limits, and right hand side consideration range limits for decimals and their relationship to binary, leading to one more limit per type, three each.  This has been possible since the inclusion of SSE CPU registers, and their descendants, in modern AMD and Intel CPU chips.  SSE and equivalent does exist in the vast majority of relevant and ubiquitous, compatible desktop PC CPU hardware today (2022).  Its registers, bit memory locations, can be leveraged to solve these value conclusion and translation error problems.  This way, accuracy of all possible decimal and hexadecimal values can be maintained, and degrading of the decimal digits can be kept outside the decimal value range limit, with no range internal errors at all at the furthest right hand side place past the dot separator, for base 10 and base 16, either from base 2.  Just as the floating point equation has an asymptote that can be followed further, the decimal place floating point range asymptotes towards truncated range accuracy, which can be upheld within a range with SSE registers and enhanced arithmetic and function logic.

Consider what GNU C++ has done with SSE and floating point decimal accuracy:

```
//The C++ Language. Arithmetic only, no comparisons.
#include <iostream>
#include <iomanip>

using namespace std;

int main() 
{
    cout << "Program has started..." << endl;
    setprecision(-9); 
    float a = 0.1F; 
    float b = 0.1F;
    float c = a*b;
    cout << endl << c << endl;
    /*
    setprecision(2); //Multiplication count from left to right.
    d = 0.1F; 
    e = 0.1F;
    f = d*e;
    cout << endl << f << endl;
    */
    setprecision(-18); 
    double d = 0.1D;   
    double e = 0.1D;   
    double f = d*e;
    cout << endl << f << endl;
    cout << endl; 
    /*
    cout << setprecision(2); //Multiplication count from left to right.
    a = 0.1D;   
    b = 0.1D;   
    c = a*b;
    cout << endl << c << endl << endl;
    */
    cout << "Program has Finished.";
    return 0;
}
```
**Program has started...**

**0.01**

**0.01**

**Program has Finished.**

Without using setPrecision to scale the view, the default float and double view and use range is visibly within that of Java.  This visibility range can be tantamount to a stronger range limit, leaving the matter quite applicable, correctable and transferable, from a C++ (C implementation) approach to a Java sub-implementation correction effort.
```

****************************************************************
Java Primitive Floating Point Range Examples

float:     32 bits, 3.4e-038 to 3.4e+038 

double:    64 bits, 1.7e-308 to 1.7e+308 

C++ Primitive Floating Point Range Examples

float:     32 bits, 1.2E-38 to 3.4E+38

double:    64 bits, 2.3E-308 to 1.7E+308
****************************************************************
```

In Java and C++, the upper ranges for double are equal.  In C++, the lower range for double is lower than the lower range for Java.

In Java, the ranges for float and double are equally far away and symmetrical around zero, in the positive and negative directions, a nicety that C++ doesn't have for the same types.  So given that C++ has succeeded, at acceptable running speeds for greater ranges, with C implementation code, why shouldn't Java just choose to do similar?  GNU C++ even avails its source and resource codes for any free, acknowledged use; this could be studied and refactored in to an OpenJDK, under a switch option or separate patch files.

Is the Alibaba Java team able to update its JDK and JRE offerings for all platforms, to either repair at default or at switched capability, these floating point logic errors?

**Comment by D-D-H** [comment]
Sorry, Dragonwell needs to keep consistent with the upstream OpenJDK.

I think the OpenJDK mail-list is the best place to discuss this issue, I noticed you have already raised the same issue there.
