### ISSUE TITLE
dragonwell-8.11.12_jdk8u332-ga 这个tag是基于openjdk哪个版本开发的？

### ISSUE THREAD

**Issue by YANGJINJUE** [alibaba/dragonwell8#350]
dragonwell-8.11.12_jdk8u332-ga 这个tag是基于openjdk哪个版本开发的？

**Comment by ziyilin** [comment]
8u332，答案就在版本号里

**Comment by YANGJINJUE** [comment]
> 8u332，答案就在版本号里

![image](https://user-images.githubusercontent.com/32013488/179506012-6149a759-2626-4c3b-a362-4e369f169e52.png)
对应这里的哪个tags? https://github.com/openjdk/jdk
