### ISSUE TITLE
[Bug] Cannot select Windows platform in https://dragonwell-jdk.io/

### ISSUE THREAD

**Issue by DevDengChao** [alibaba/dragonwell8#387]
**Description**

![image](https://user-images.githubusercontent.com/16363180/182144467-459a7b97-5604-40b4-b41e-26191f7a1062.png)

**Steps to Reproduce**

1. Visit  https://dragonwell-jdk.io/

**Expected behavior**

There should be an option for Windows as the releases contains Windows binaries.

**Comment by Accelerator1996** [comment]
Hi, DevDengChao, thanks for the reminder, we have fixed this problem
