### ISSUE TITLE
Add install instructions for Alibaba Cloud Linux 2

### ISSUE THREAD

**Issue by yfxhust** [alibaba/dragonwell8#39]
**Description**
Alibaba Cloud Linux 2 already integrated Dragonwell JDK. readme.md should add install instructions for Alibaba Cloud Linux 2.

**Steps to Reproduce**
Review readme.md.

**Expected behavior**
Readme.md should contain install instructions for Alibaba Cloud Linux 2

**JDK version**
Any

**Execution environment**
Any

**Comment by luchsh** [comment]
@yfxhust any progress on this issue? shall we close it for now

**Comment by yfxhust** [comment]
already fixed. The pr from casparant is already pushed.
