### ISSUE TITLE
git clone the alibaba private repos, we are outside alibaba inc

### ISSUE THREAD

**Issue by netroby** [alibaba/dragonwell8#4]
when we run `$ sh get_source_dragonwell.sh`
can not clone repo , because it by default request alibaba private repos
```
Start clone...
/usr/bin/git clone git@gitlab.alibaba-inc.com:dragonwell/jdk8u_corba.git corba
Cloning into 'corba'...

```

**Comment by kuaiwei** [comment]
please use "get_source_dragonwell.sh -s github" to get sub modules
The default option is used internal.

**Comment by netroby** [comment]
I read the code, and know the cause. but please let me close my issue , i can handle it.  do not just close user issue directly, we can communicate.

**Comment by yansendao** [comment]
> I read the code, and know the cause. but please let me close my issue , i can handle it. do not just close user issue directly, we can communicate.

Good idea!
