### ISSUE TITLE
one billion lines of Java code

### ISSUE THREAD

**Issue by foldl** [alibaba/dragonwell8#413]
**Description**
In the readme:

> many our Java developers have written more than one billion lines of Java code.

Is this possible? Does it have anything to do with this project?

**Comment by foldl** [comment]
https://github.com/alibaba/dragonwell8/blob/b0b8f7d7bc3c691bf8b0a10983f6c7a8a026d7e5/README.md?plain=1#L9

**Comment by D-D-H** [comment]
What the sentence in the readme wants to express is that there are a large number of java applications inside Alibaba, and the code of all the applications adds up to more than one billion lines. The amount of code itself has nothing to do with this project.

**Comment by foldl** [comment]
No.

The sentence means that, **each** of those outstanding Java developers has written more than one billion lines of Java code.

**Comment by D-D-H** [comment]
> No.
> 
> The sentence means that, **each** of those outstanding Java developers has written more than one billion lines of Java code.

Hmmm, you are right. We should remove the 'many' from 'many our Java developers'.

**Comment by luchsh** [comment]
> No.
> 
> The sentence means that, **each** of those outstanding Java developers has written more than one billion lines of Java code.

I do not see the word "outstanding Java developers" from README, did you?
They were just trying to say it was a big code base.

If you wanna be objective and try to reason about a strict standard for 'line of code', please feel free to write a paper to present your questions and ideas.

This project is about a downstream JDK provided freely to Aliyun clients, the codebase size is just a evidence of wide adoption, not to say 'proudly' that these folks are 'outstanding Java developers' as I see.

**Comment by luchsh** [comment]
> > No.
> > The sentence means that, **each** of those outstanding Java developers has written more than one billion lines of Java code.
> 
> Hmm, you are right. We should remove the 'many' from 'many our Java developers'.

No, he is not!

**Comment by luchsh** [comment]
> 

are you serious about this?

this phrase has been widely used in other places, see

https://www.engadget.com/2015-09-18-googles-codebase-is-ludicrously-huge-for-good-reason.html#:~:text=Google's%20codebase%20%2D%2D%20the%20programming,Google%20engineering%20manager%20Rachel%20Potvin.

https://devblogs.microsoft.com/bharry/the-largest-git-repo-on-the-planet/#:~:text=As%20a%20refresher%2C%20the%20Windows,a%20repo%20of%20about%20300GB.

any more questions to Google or Microsoft?

**Comment by zhengxiaolinX** [comment]
I guess we can do some more practical work than this. Close this first.

**Comment by foldl** [comment]
> If you wanna be objective and try to reason about a strict standard for 'line of code', please feel free to write a paper to present your questions and ideas.

I have already asked for your definition of "write one line of code".

**Comment by foldl** [comment]
> I guess we can do some more practical work than this.

Do you think the first paragraph in Readme is a piece of practical work?

**Comment by foldl** [comment]
> https://devblogs.microsoft.com/bharry/the-largest-git-repo-on-the-planet/#:~:text=As%20a%20refresher%2C%20the%20Windows,a%20repo%20of%20about%20300GB.

> As a refresher, the Windows code base is approximately 3.5M files and, when checked in to a Git repo, results in a repo of about 300GB.

Calculation of all these number are clear. Now, once again, how about "one billion lines of Java code"?
