### ISSUE TITLE
如何编译这个JDK

### ISSUE THREAD

**Issue by elizax** [alibaba/dragonwell8#414]
./configure && make all
编译langtools 的java文件一直报错 缺少包

**Comment by D-D-H** [comment]
按照错误提示安装下缺少的依赖包。

如果可以的话，提供下报错信息。

**Comment by elizax** [comment]
> 按照错误提示安装下缺少的依赖包。
> 
> 如果可以的话，提供下报错信息。

**Comment by elizax** [comment]
![5d8245692c378cc85c16e3390c22b0e](https://user-images.githubusercontent.com/16499716/195777818-ddda0dfc-f211-44e7-98e5-20046adcd219.jpg)

手动往langtools拷贝jdk文件夹下的文件，但觉得不应该这样，而且最终还是缺少java 包

**Comment by D-D-H** [comment]
> ![5d8245692c378cc85c16e3390c22b0e](https://user-images.githubusercontent.com/16499716/195777818-ddda0dfc-f211-44e7-98e5-20046adcd219.jpg)
> 
> 手动往langtools拷贝jdk文件夹下的文件，但觉得不应该这样，而且最终还是缺少java 包

你使用的 boot-jdk 是什么版本？

**Comment by D-D-H** [comment]
建议你可以先下载一个对应平台的 dragonwell8 构建，然后 bash ./configure --with-boot-jdk=<path-to-jdk8>

**Comment by elizax** [comment]
> 建议你可以先下载一个对应平台的 dragonwell8 构建，然后 bash ./configure --with-boot-jdk=<path-to-jdk8>

用的自带的open jdk 8 arm版，boot-jdk换了dragonwell8就可以编译过了，感谢
