### ISSUE TITLE
jwarmup录制时间到后jvm崩溃

### ISSUE THREAD

**Issue by WangZaier** [alibaba/dragonwell8#420]
项目为springboot项目，直接使用jar启动。
Dragonwell版本为 8.12.13

---------------  T H R E A D  ---------------

Current thread is native thread

siginfo: ExceptionCode=0xc0000005, reading address 0x00000000000001c8

Registers:
RAX=0x0000000000000000, RBX=0x00000195042e4a50, RCX=0x0000000000000011, RDX=0x0000000000000003
RSP=0x000000516e3ff940, RBP=0x000000516e3ffde0, RSI=0x0000019504303f90, RDI=0x0000019504303f90
R8 =0x0000000000000024, R9 =0x0000019526cab010, R10=0x0000000077f6c421, R11=0x0000019526cab011
R12=0x0000000000000000, R13=0x0000000000000000, R14=0x0000000000000000, R15=0x0000000000000000
RIP=0x00000000778210dd, EFLAGS=0x0000000000010206

Top of Stack: (sp=0x000000516e3ff940)
0x000000516e3ff940:   0000000000000024 00007ffb40c4c500
0x000000516e3ff950:   0000000000000000 0000000077f6c420
0x000000516e3ff960:   0000000000000000 0000000000000000
0x000000516e3ff970:   0000000000000000 0000000000000000
0x000000516e3ff980:   0000000000000000 000001951a10c6d0
0x000000516e3ff990:   0000019504303f90 000000516e3ffde0
0x000000516e3ff9a0:   00000195042e4a50 000000007781e112
0x000000516e3ff9b0:   00000195042e4a50 0000019504303f90
0x000000516e3ff9c0:   000001951a10c6d0 00007ffb40c4c500
0x000000516e3ff9d0:   000001950438a450 000000007781e2a3
0x000000516e3ff9e0:   000000516e3ffde0 000001951a10b490
0x000000516e3ff9f0:   000001951a10c6d0 000001951a10b490
0x000000516e3ffa00:   000001951a10d800 0000000077821a76
0x000000516e3ffa10:   000001951a10d800 0000019500000002
0x000000516e3ffa20:   0000000000000000 0000000000000000
0x000000516e3ffa30:   000001951a10d800 00000000779e06fa 

Instructions: (pc=0x00000000778210dd)
0x00000000778210bd:   48 83 ec 28 48 8b f9 e8 47 ce 16 00 84 c0 74 0e
0x00000000778210cd:   8b 0d f1 55 6f 00 ff 15 f7 52 51 00 eb 02 33 c0
0x00000000778210dd:   4c 8b a8 c8 01 00 00 8b 5f 18 48 8d 15 22 af 74
0x00000000778210ed:   00 49 8b 75 18 49 8b 6d 20 4d 8b 75 28 4d 8b 65 

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x00000195042e4a50 is an unknown value
RCX=0x0000000000000011 is an unknown value
RDX=0x0000000000000003 is an unknown value
RSP=0x000000516e3ff940 is an unknown value
RBP=0x000000516e3ffde0 is an unknown value
RSI=0x0000019504303f90 is an unknown value
RDI=0x0000019504303f90 is an unknown value
R8 =0x0000000000000024 is an unknown value
R9 =0x0000019526cab010 is an unknown value
R10=0x0000000077f6c421 is an unknown value
R11=0x0000019526cab011 is an unknown value
R12=0x0000000000000000 is an unknown value
R13=0x0000000000000000 is an unknown value
R14=0x0000000000000000 is an unknown value
R15=0x0000000000000000 is an unknown value

Stack: [0x000000516e300000,0x000000516e400000],  sp=0x000000516e3ff940,  free space=1022k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [jvm.dll+0xb10dd]
V  [jvm.dll+0xae112]
V  [jvm.dll+0xae2a3]
V  [jvm.dll+0xb1a76]
V  [jvm.dll+0x2706fa]
C  [msvcr120.dll+0x24f7f]
C  [msvcr120.dll+0x25126]
C  [KERNEL32.DLL+0x17034]
C  [ntdll.dll+0x526a1]

---------------  P R O C E S S  ---------------

VM state:not at safepoint (normal execution)

VM Mutex/Monitor currently owned by a thread: None

heap address: 0x0000000081c00000, size: 2020 MB, Compressed Oops mode: 32-bit
Narrow klass base: 0x0000000000000000, Narrow klass shift: 3
Compressed class space size: 1073741824 Address: 0x0000000100000000

Heap:
 par new generation   total 39424K, used 22158K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K,  51% used [0x0000000081c00000, 0x0000000082d99518, 0x0000000083e40000)
  from space 4352K,  95% used [0x0000000084280000, 0x000000008468a500, 0x00000000846c0000)
  to   space 4352K,   0% used [0x0000000083e40000, 0x0000000083e40000, 0x0000000084280000)
 concurrent mark-sweep generation total 87424K, used 42286K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 92495K, capacity 97182K, committed 97408K, reserved 1134592K
  class space    used 12318K, capacity 13090K, committed 13184K, reserved 1048576K

Card table byte_map: [0x0000019515440000,0x0000019515840000] byte_map_base: 0x0000019515032000

Marking Bits: (CMSBitMap*) 0x00000195043883f0
 Bits: [0x0000019516260000, 0x0000019517789c00)

Mod Union Table: (CMSBitMap*) 0x00000195043884b0
 Bits: [0x00000195043c0000, 0x0000019504414a70)

Polling page: 0x0000019504280000

CodeCache: size=245760Kb used=21879Kb max_used=22248Kb free=223880Kb
 bounds [0x0000019506080000, 0x0000019507660000, 0x0000019515080000]
 total_blobs=7423 nmethods=6748 adapters=582
 compilation: enabled

Compilation events (10 events):
Event: 57.787 Thread 0x000001951a563000 8073       3       java.nio.ByteBuffer::order (48 bytes)
Event: 57.787 Thread 0x000001951a563000 nmethod 8073 0x0000019507636650 code [0x00000195076367c0, 0x0000019507636a58]
Event: 57.787 Thread 0x000001951a563000 8074       1       org.bson.BsonElement::getName (5 bytes)
Event: 57.788 Thread 0x000001951a563000 nmethod 8074 0x0000019507636390 code [0x00000195076364e0, 0x00000195076365f8]
Event: 58.561 Thread 0x000001951a563000 8075       3       java.util.concurrent.locks.LockSupport::setBlocker (12 bytes)
Event: 58.561 Thread 0x000001951a563000 nmethod 8075 0x0000019507636050 code [0x00000195076361a0, 0x00000195076362f8]
Event: 59.398 Thread 0x000001951a563000 8076       3       java.util.concurrent.locks.AbstractQueuedSynchronizer::compareAndSetWaitStatus (13 bytes)
Event: 59.398 Thread 0x000001951a563000 nmethod 8076 0x0000019507635d10 code [0x0000019507635e60, 0x0000019507635fb8]
Event: 59.398 Thread 0x000001951a563000 8077       1       org.apache.catalina.LifecycleEvent::getType (5 bytes)
Event: 59.398 Thread 0x000001951a563000 nmethod 8077 0x0000019507635a50 code [0x0000019507635ba0, 0x0000019507635cb8]

GC Heap History (10 events):
Event: 17.759 GC heap before
{Heap before GC invocations=102 (full 3):
 par new generation   total 39424K, used 38068K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K, 100% used [0x0000000081c00000, 0x0000000083e40000, 0x0000000083e40000)
  from space 4352K,  68% used [0x0000000083e40000, 0x000000008412d0a0, 0x0000000084280000)
  to   space 4352K,   0% used [0x0000000084280000, 0x0000000084280000, 0x00000000846c0000)
 concurrent mark-sweep generation total 87424K, used 39630K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 89180K, capacity 93572K, committed 93824K, reserved 1130496K
  class space    used 11882K, capacity 12587K, committed 12672K, reserved 1048576K
Event: 17.763 GC heap after
Heap after GC invocations=103 (full 3):
 par new generation   total 39424K, used 4054K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K,   0% used [0x0000000081c00000, 0x0000000081c00000, 0x0000000083e40000)
  from space 4352K,  93% used [0x0000000084280000, 0x0000000084675a68, 0x00000000846c0000)
  to   space 4352K,   0% used [0x0000000083e40000, 0x0000000083e40000, 0x0000000084280000)
 concurrent mark-sweep generation total 87424K, used 39630K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 89180K, capacity 93572K, committed 93824K, reserved 1130496K
  class space    used 11882K, capacity 12587K, committed 12672K, reserved 1048576K
}
Event: 17.970 GC heap before
{Heap before GC invocations=103 (full 3):
 par new generation   total 39424K, used 39126K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K, 100% used [0x0000000081c00000, 0x0000000083e40000, 0x0000000083e40000)
  from space 4352K,  93% used [0x0000000084280000, 0x0000000084675a68, 0x00000000846c0000)
  to   space 4352K,   0% used [0x0000000083e40000, 0x0000000083e40000, 0x0000000084280000)
 concurrent mark-sweep generation total 87424K, used 39630K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 89958K, capacity 94446K, committed 94720K, reserved 1130496K
  class space    used 12004K, capacity 12718K, committed 12800K, reserved 1048576K
Event: 17.977 GC heap after
Heap after GC invocations=104 (full 3):
 par new generation   total 39424K, used 2955K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K,   0% used [0x0000000081c00000, 0x0000000081c00000, 0x0000000083e40000)
  from space 4352K,  67% used [0x0000000083e40000, 0x0000000084122fd0, 0x0000000084280000)
  to   space 4352K,   0% used [0x0000000084280000, 0x0000000084280000, 0x00000000846c0000)
 concurrent mark-sweep generation total 87424K, used 41265K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 89958K, capacity 94446K, committed 94720K, reserved 1130496K
  class space    used 12004K, capacity 12718K, committed 12800K, reserved 1048576K
}
Event: 18.151 GC heap before
{Heap before GC invocations=104 (full 3):
 par new generation   total 39424K, used 38027K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K, 100% used [0x0000000081c00000, 0x0000000083e40000, 0x0000000083e40000)
  from space 4352K,  67% used [0x0000000083e40000, 0x0000000084122fd0, 0x0000000084280000)
  to   space 4352K,   0% used [0x0000000084280000, 0x0000000084280000, 0x00000000846c0000)
 concurrent mark-sweep generation total 87424K, used 41265K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 90694K, capacity 95254K, committed 95616K, reserved 1132544K
  class space    used 12080K, capacity 12814K, committed 12928K, reserved 1048576K
Event: 18.154 GC heap after
Heap after GC invocations=105 (full 3):
 par new generation   total 39424K, used 2953K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K,   0% used [0x0000000081c00000, 0x0000000081c00000, 0x0000000083e40000)
  from space 4352K,  67% used [0x0000000084280000, 0x00000000845624b0, 0x00000000846c0000)
  to   space 4352K,   0% used [0x0000000083e40000, 0x0000000083e40000, 0x0000000084280000)
 concurrent mark-sweep generation total 87424K, used 41265K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 90694K, capacity 95254K, committed 95616K, reserved 1132544K
  class space    used 12080K, capacity 12814K, committed 12928K, reserved 1048576K
}
Event: 18.312 GC heap before
{Heap before GC invocations=105 (full 3):
 par new generation   total 39424K, used 38025K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K, 100% used [0x0000000081c00000, 0x0000000083e40000, 0x0000000083e40000)
  from space 4352K,  67% used [0x0000000084280000, 0x00000000845624b0, 0x00000000846c0000)
  to   space 4352K,   0% used [0x0000000083e40000, 0x0000000083e40000, 0x0000000084280000)
 concurrent mark-sweep generation total 87424K, used 41265K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 91088K, capacity 95554K, committed 95872K, reserved 1132544K
  class space    used 12138K, capacity 12850K, committed 12928K, reserved 1048576K
Event: 18.316 GC heap after
Heap after GC invocations=106 (full 3):
 par new generation   total 39424K, used 3683K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K,   0% used [0x0000000081c00000, 0x0000000081c00000, 0x0000000083e40000)
  from space 4352K,  84% used [0x0000000083e40000, 0x00000000841d8eb0, 0x0000000084280000)
  to   space 4352K,   0% used [0x0000000084280000, 0x0000000084280000, 0x00000000846c0000)
 concurrent mark-sweep generation total 87424K, used 41692K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 91088K, capacity 95554K, committed 95872K, reserved 1132544K
  class space    used 12138K, capacity 12850K, committed 12928K, reserved 1048576K
}
Event: 18.589 GC heap before
{Heap before GC invocations=106 (full 3):
 par new generation   total 39424K, used 38755K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K, 100% used [0x0000000081c00000, 0x0000000083e40000, 0x0000000083e40000)
  from space 4352K,  84% used [0x0000000083e40000, 0x00000000841d8eb0, 0x0000000084280000)
  to   space 4352K,   0% used [0x0000000084280000, 0x0000000084280000, 0x00000000846c0000)
 concurrent mark-sweep generation total 87424K, used 41692K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 92140K, capacity 96728K, committed 96768K, reserved 1132544K
  class space    used 12264K, capacity 13019K, committed 13056K, reserved 1048576K
Event: 18.594 GC heap after
Heap after GC invocations=107 (full 3):
 par new generation   total 39424K, used 4137K [0x0000000081c00000, 0x00000000846c0000, 0x00000000ab590000)
  eden space 35072K,   0% used [0x0000000081c00000, 0x0000000081c00000, 0x0000000083e40000)
  from space 4352K,  95% used [0x0000000084280000, 0x000000008468a500, 0x00000000846c0000)
  to   space 4352K,   0% used [0x0000000083e40000, 0x0000000083e40000, 0x0000000084280000)
 concurrent mark-sweep generation total 87424K, used 42286K [0x00000000ab590000, 0x00000000b0af0000, 0x0000000100000000)
 Metaspace       used 92140K, capacity 96728K, committed 96768K, reserved 1132544K
  class space    used 12264K, capacity 13019K, committed 13056K, reserved 1048576K
}

Deoptimization events (10 events):
Event: 18.568 Thread 0x00000195042f4800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x000001950680542c method=java.util.regex.Matcher.search(I)Z @ 86
Event: 18.585 Thread 0x00000195042f4800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x00000195065db610 method=java.util.HashMap.getNode(ILjava/lang/Object;)Ljava/util/HashMap$Node; @ 129
Event: 18.642 Thread 0x00000195042f4800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x000001950712a1e0 method=java.util.HashMap.computeIfAbsent(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object; @ 142
Event: 18.647 Thread 0x00000195042f4800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x000001950712a1e0 method=java.util.HashMap.computeIfAbsent(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object; @ 142
Event: 18.650 Thread 0x00000195042f4800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x000001950712a1e0 method=java.util.HashMap.computeIfAbsent(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object; @ 142
Event: 18.650 Thread 0x00000195042f4800 Uncommon trap: reason=bimorphic action=maybe_recompile pc=0x000001950712a1e0 method=java.util.HashMap.computeIfAbsent(Ljava/lang/Object;Ljava/util/function/Function;)Ljava/lang/Object; @ 142
Event: 18.654 Thread 0x00000195042f4800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000019506662d90 method=java.util.HashMap.getNode(ILjava/lang/Object;)Ljava/util/HashMap$Node; @ 84
Event: 18.654 Thread 0x00000195042f4800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000019506fc99f8 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 109
Event: 18.654 Thread 0x00000195042f4800 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000019506688ad8 method=java.util.HashMap.putVal(ILjava/lang/Object;Ljava/lang/Object;ZZ)Ljava/lang/Object; @ 162
Event: 48.684 Thread 0x000001951f4c8000 Uncommon trap: reason=unstable_if action=reinterpret pc=0x0000019506b83ff4 method=java.lang.ThreadLocal.get()Ljava/lang/Object; @ 11

Classes redefined (0 events):
No events

Internal exceptions (10 events):
Event: 18.164 Thread 0x00000195042f4800 Exception <a 'java/lang/ClassNotFoundException': org/springframework/data/keyvalue/core/KeyValueAdapterCustomizer> (0x00000000821a73e0) thrown at [C:\workspace\openjdk-build\workspace\build\src\hotspot\src\share\vm\classfile\systemDictionary.cpp, line 217
Event: 18.167 Thread 0x00000195042f4800 Exception <a 'java/lang/ClassNotFoundException': org/springframework/beans/factory/DisposableBeanCustomizer> (0x000000008226d438) thrown at [C:\workspace\openjdk-build\workspace\build\src\hotspot\src\share\vm\classfile\systemDictionary.cpp, line 217]
Event: 18.287 Thread 0x00000195042f4800 Exception <a 'java/lang/ClassNotFoundException': org/quartz/simpl/SimpleThreadPoolBeanInfo> (0x000000008378a388) thrown at [C:\workspace\openjdk-build\workspace\build\src\hotspot\src\share\vm\classfile\systemDictionary.cpp, line 217]
Event: 18.287 Thread 0x00000195042f4800 Exception <a 'java/lang/ClassNotFoundException': java/lang/ObjectBeanInfo> (0x00000000837cdf80) thrown at [C:\workspace\openjdk-build\workspace\build\src\hotspot\src\share\vm\classfile\systemDictionary.cpp, line 217]
Event: 18.288 Thread 0x00000195042f4800 Exception <a 'java/lang/ClassNotFoundException': java/lang/ObjectCustomizer> (0x0000000083812798) thrown at [C:\workspace\openjdk-build\workspace\build\src\hotspot\src\share\vm\classfile\systemDictionary.cpp, line 217]
Event: 18.289 Thread 0x00000195042f4800 Exception <a 'java/lang/ClassNotFoundException': org/quartz/simpl/SimpleThreadPoolCustomizer> (0x00000000838b7338) thrown at [C:\workspace\openjdk-build\workspace\build\src\hotspot\src\share\vm\classfile\systemDictionary.cpp, line 217]
Event: 18.307 Thread 0x00000195042f4800 Exception <a 'java/lang/ClassNotFoundException': org/quartz/simpl/RAMJobStoreBeanInfo> (0x0000000083cdbd98) thrown at [C:\workspace\openjdk-build\workspace\build\src\hotspot\src\share\vm\classfile\systemDictionary.cpp, line 217]
Event: 18.308 Thread 0x00000195042f4800 Exception <a 'java/lang/ClassNotFoundException': org/quartz/simpl/RAMJobStoreCustomizer> (0x0000000083d74500) thrown at [C:\workspace\openjdk-build\workspace\build\src\hotspot\src\share\vm\classfile\systemDictionary.cpp, line 217]
Event: 18.644 Thread 0x00000195042f4800 Exception <a 'java/lang/NoSuchMethodError': java.lang.Object.lambda$byPatternsCondition$0(Lspringfox/documentation/RequestHandler;)Ljava/lang/String;> (0x00000000825af808) thrown at [C:\workspace\openjdk-build\workspace\build\src\hotspot\src\share\vm\inte
Event: 48.684 Thread 0x000001951f4c8000 Implicit null exception at 0x0000019506b83f22 to 0x0000019506b83fe1

Events (10 events):
Event: 48.684 Thread 0x000001951f4c8000 Uncommon trap: trap_request=0xffffff65 fr.pc=0x0000019506b83ff4
Event: 48.684 Thread 0x000001951f4c8000 DEOPT PACKING pc=0x0000019506b83ff4 sp=0x00000051713fee10
Event: 48.684 Thread 0x000001951f4c8000 DEOPT UNPACKING pc=0x00000195060c5583 sp=0x00000051713feda8 mode 2
Event: 48.684 Executing VM operation: RevokeBias
Event: 48.684 Executing VM operation: RevokeBias done
Event: 48.685 Thread 0x000001951f4c8000 DEOPT PACKING pc=0x000001950626907e sp=0x00000051713fea80
Event: 48.685 Thread 0x000001951f4c8000 DEOPT UNPACKING pc=0x00000195060c75d8 sp=0x00000051713fe790 mode 0
Event: 48.685 Executing VM operation: RevokeBias
Event: 48.685 Executing VM operation: RevokeBias done
Event: 48.685 Thread 0x000001951f4c8000 Thread exited: 0x000001951f4c8000

Dynamic libraries:
0x00007ff7c27e0000 - 0x00007ff7c281a000 	D:\dragonwell\alijdk\dragonwell-8.12.13\bin\java.exe
0x00007ffb629f0000 - 0x00007ffb62be8000 	C:\WINDOWS\SYSTEM32\ntdll.dll
0x00007ffb61860000 - 0x00007ffb6191d000 	C:\WINDOWS\System32\KERNEL32.DLL
0x00007ffb60300000 - 0x00007ffb605d2000 	C:\WINDOWS\System32\KERNELBASE.dll
0x00007ffb61ab0000 - 0x00007ffb61b5e000 	C:\WINDOWS\System32\ADVAPI32.dll
0x00007ffb60af0000 - 0x00007ffb60b8e000 	C:\WINDOWS\System32\msvcrt.dll
0x00007ffb60a50000 - 0x00007ffb60aec000 	C:\WINDOWS\System32\sechost.dll
0x00007ffb61e40000 - 0x00007ffb61f65000 	C:\WINDOWS\System32\RPCRT4.dll
0x00007ffb60d50000 - 0x00007ffb60eed000 	C:\WINDOWS\System32\USER32.dll
0x00007ffb607f0000 - 0x00007ffb60812000 	C:\WINDOWS\System32\win32u.dll
0x00007ffb60f50000 - 0x00007ffb60f7b000 	C:\WINDOWS\System32\GDI32.dll
0x00007ffb60690000 - 0x00007ffb6079f000 	C:\WINDOWS\System32\gdi32full.dll
0x00007ffb60980000 - 0x00007ffb60a1d000 	C:\WINDOWS\System32\msvcp_win.dll
0x00007ffb60190000 - 0x00007ffb60290000 	C:\WINDOWS\System32\ucrtbase.dll
0x00007ffb4c4c0000 - 0x00007ffb4c75a000 	C:\WINDOWS\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e\COMCTL32.dll
0x00007ffb613b0000 - 0x00007ffb613e0000 	C:\WINDOWS\System32\IMM32.DLL
0x0000000052700000 - 0x000000005270c000 	D:\11dsy\360\360Safe\safemon\SafeWrapper.dll
0x00007ffb49fa0000 - 0x00007ffb4a036000 	D:\11dsy\360\360Safe\safemon\libzdtp64.dll
0x00007ffb62260000 - 0x00007ffb629a3000 	C:\WINDOWS\System32\SHELL32.dll
0x00007ffb61be0000 - 0x00007ffb61c35000 	C:\WINDOWS\System32\SHLWAPI.dll
0x00007ffb5fcb0000 - 0x00007ffb5fcba000 	C:\WINDOWS\SYSTEM32\VERSION.dll
0x00007ffb40b70000 - 0x00007ffb40c5f000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\msvcr120.dll
0x00007ffb15160000 - 0x00007ffb15206000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\msvcp120.dll
0x0000000077770000 - 0x0000000077ffb000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\server\jvm.dll
0x00007ffb62120000 - 0x00007ffb62128000 	C:\WINDOWS\System32\PSAPI.DLL
0x00007ffb4e3e0000 - 0x00007ffb4e407000 	C:\WINDOWS\SYSTEM32\WINMM.dll
0x00007ffb4b670000 - 0x00007ffb4b679000 	C:\WINDOWS\SYSTEM32\WSOCK32.dll
0x00007ffb61980000 - 0x00007ffb619eb000 	C:\WINDOWS\System32\WS2_32.dll
0x00007ffb5a500000 - 0x00007ffb5a50f000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\verify.dll
0x00007ffb5a4d0000 - 0x00007ffb5a4fa000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\java.dll
0x00007ffb4b850000 - 0x00007ffb4b866000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\zip.dll
0x00007ffb5dd40000 - 0x00007ffb5e4d1000 	C:\WINDOWS\SYSTEM32\windows.storage.dll
0x00007ffb61050000 - 0x00007ffb613a4000 	C:\WINDOWS\System32\combase.dll
0x00007ffb5faf0000 - 0x00007ffb5fb20000 	C:\WINDOWS\SYSTEM32\Wldp.dll
0x00007ffb61a00000 - 0x00007ffb61aad000 	C:\WINDOWS\System32\SHCORE.dll
0x00007ffb60040000 - 0x00007ffb6005f000 	C:\WINDOWS\SYSTEM32\profapi.dll
0x00007ffb59970000 - 0x00007ffb5997d000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\management.dll
0x00007ffb43610000 - 0x00007ffb4362a000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\net.dll
0x00007ffb5f830000 - 0x00007ffb5f89a000 	C:\WINDOWS\system32\mswsock.dll
0x00007ffb43e60000 - 0x00007ffb43e77000 	C:\WINDOWS\system32\napinsp.dll
0x00007ffb40670000 - 0x00007ffb4068b000 	C:\WINDOWS\system32\pnrpnsp.dll
0x00007ffb5a7b0000 - 0x00007ffb5a7c5000 	C:\WINDOWS\system32\wshbth.dll
0x00007ffb5b560000 - 0x00007ffb5b57d000 	C:\WINDOWS\system32\NLAapi.dll
0x00007ffb5f4c0000 - 0x00007ffb5f4fb000 	C:\WINDOWS\SYSTEM32\IPHLPAPI.DLL
0x00007ffb5f500000 - 0x00007ffb5f5ca000 	C:\WINDOWS\SYSTEM32\DNSAPI.dll
0x00007ffb619f0000 - 0x00007ffb619f8000 	C:\WINDOWS\System32\NSI.dll
0x00007ffb40620000 - 0x00007ffb40632000 	C:\WINDOWS\System32\winrnr.dll
0x00007ffb4db00000 - 0x00007ffb4db0a000 	C:\Windows\System32\rasadhlp.dll
0x00007ffb54730000 - 0x00007ffb547b0000 	C:\WINDOWS\System32\fwpuclnt.dll
0x00007ffb60a20000 - 0x00007ffb60a47000 	C:\WINDOWS\System32\bcrypt.dll
0x00007ffb43230000 - 0x00007ffb43253000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\sunec.dll
0x00007ffb5fa50000 - 0x00007ffb5fa68000 	C:\WINDOWS\SYSTEM32\CRYPTSP.dll
0x00007ffb5f050000 - 0x00007ffb5f084000 	C:\WINDOWS\system32\rsaenh.dll
0x00007ffb60000000 - 0x00007ffb6002e000 	C:\WINDOWS\SYSTEM32\USERENV.dll
0x00007ffb60100000 - 0x00007ffb60182000 	C:\WINDOWS\System32\bcryptprimitives.dll
0x00007ffb5fa40000 - 0x00007ffb5fa4c000 	C:\WINDOWS\SYSTEM32\CRYPTBASE.dll
0x00007ffb54c20000 - 0x00007ffb54c37000 	C:\WINDOWS\SYSTEM32\dhcpcsvc6.DLL
0x00007ffb54bb0000 - 0x00007ffb54bcd000 	C:\WINDOWS\SYSTEM32\dhcpcsvc.DLL
0x00007ffb435f0000 - 0x00007ffb43602000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\nio.dll
0x0000000180000000 - 0x000000018020f000 	D:\apache-tomcat-form\bin\tcnative-1.dll
0x00007ffb56690000 - 0x00007ffb5669c000 	D:\dragonwell\alijdk\dragonwell-8.12.13\jre\bin\sunmscapi.dll
0x00007ffb60820000 - 0x00007ffb60976000 	C:\WINDOWS\System32\CRYPT32.dll
0x00007ffb5fb60000 - 0x00007ffb5fb87000 	C:\WINDOWS\SYSTEM32\ncrypt.dll
0x00007ffb5fb20000 - 0x00007ffb5fb5b000 	C:\WINDOWS\SYSTEM32\NTASN1.dll
0x00007ffb5e5b0000 - 0x00007ffb5e794000 	C:\WINDOWS\SYSTEM32\dbghelp.dll

VM Arguments:
jvm_args: -XX:-ClassUnloading -XX:-CMSClassUnloadingEnabled -XX:-ClassUnloadingWithConcurrentMark -XX:CompilationWarmUpLogfile=jwarmup.log -XX:+CompilationWarmUpRecording -XX:CompilationWarmUpRecordTime=60 
java_command: workplat-starter-application.jar
java_class_path (initial): workplat-starter-application.jar
Launcher Type: SUN_STANDARD

Environment Variables:
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_211
CLASSPATH=.;C:\Program Files\Java\jdk1.8.0_211\lib;C:\Program Files\Java\jdk1.8.0_211\lib\tools.jar
PATH=C:\Users\work\bin;D:\Git\mingw64\bin;D:\Git\usr\local\bin;D:\Git\usr\bin;D:\Git\usr\bin;D:\Git\mingw64\bin;D:\Git\usr\bin;C:\Users\work\bin;C:\Program Files (x86)\Common Files\NetSarang;C:\Program Files\VanDyke Software\Clients;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;D:\apache-maven-3.6.1\bin;D:\svn\bin;D:\Git\cmd;D:\apache-tomcat-form\bin;C:\Users\work\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;C:\Users\work\.app;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;D:\Microsoft VS Code\bin;C:\Users\work\AppData\Roaming\npm;%NVM_HOME%;%NVM_SYMLINK%;C:\Users\work\AppData\Local\JetBrains\Toolbox\scripts;D:\Git\usr\bin\vendor_perl;D:\Git\usr\bin\core_perl
USERNAME=work
SHELL=D:\Git\usr\bin\bash.exe
DISPLAY=needs-to-be-defined
OS=Windows_NT
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 142 Stepping 10, GenuineIntel

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 19041 (10.0.19041.1889)

CPU:total 8 (initial active 8) (4 cores per cpu, 2 threads per core) family 6 model 142 stepping 10, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, 3dnowpref, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2, adx

Memory: 4k page, physical 8269544k(1926284k free), swap 20301348k(3079064k free)

vm_info: OpenJDK 64-Bit Server VM (25.345-b01) for windows-amd64 JRE (1.8.0_345-b01), built on Aug  8 2022 15:41:28 by "Administrator" with MS VC++ 12.0 (VS2013)

time: Tue Nov 01 16:11:01 2022
timezone: 中国标准时间
elapsed time: 60.051297 seconds (0d 0h 1m 0s)

**Comment by kuaiwei** [comment]
你是用的windows吗？目前jwarmup还不支持windows环境
