### ISSUE TITLE
Do we have a workaround to link successfully with only 1GB RAM

### ISSUE THREAD

**Issue by wyzd03105** [alibaba/dragonwell8#43]
This error happened because there's only 1GB RAM on my virtual machine. Other than expanding the memory, do we have a workaround to link successfully with only 1GB RAM?
Thanks!

Linking vm...
collect2: fatal error: ld terminated with signal 9 [Killed]
compilation terminated.
/usr/bin/ld: warning: unrecognized --build-id style ignored.
/usr/bin/objcopy: error: the input file 'libjvm.so' is empty
/root/opensource/dragonwell8/hotspot/make/linux/makefiles/vm.make:340: recipe for target 'libjvm.so' failed
make[6]: *** [libjvm.so] Error 1
make[5]: *** [the_vm] Error 2
make[4]: *** [product] Error 2
make[3]: *** [generic_build2] Error 2
make[2]: *** [product] Error 2
make[1]: *** [/root/opensource/dragonwell8/build/linux-x86_64-normal-server-release/hotspot/_hotspot.timestamp] Error 2
/root/opensource/dragonwell8/hotspot/make/linux/makefiles/top.make:119: recipe for target 'the_vm' failed
/root/opensource/dragonwell8/hotspot/make/linux/Makefile:284: recipe for target 'product' failed
Makefile:230: recipe for target 'generic_build2' failed
Makefile:177: recipe for target 'product' failed
HotspotWrapper.gmk:44: recipe for target '/root/opensource/dragonwell8/build/linux-x86_64-normal-server-release/hotspot/_hotspot.timestamp' failed
/root/opensource/dragonwell8//make/Main.gmk:109: recipe for target 'hotspot-only' failed
make: *** [hotspot-only] Error 2

**Comment by D-D-H** [comment]
You can try to add a configure "--with-memory-size=<size>",  it will select the RAM size that GNU make will think the system has.
Another possible way is to increase the amount of swap space on your build machine.
More information can be found on README-builds.html.

**Comment by wyzd03105** [comment]
Thanks!
