### ISSUE TITLE
[Bug] Mini-heapdump might be the default mode when FGC happens

### ISSUE THREAD

**Issue by luchsh** [alibaba/dragonwell8#45]
**Description**
Mini-heapdump is the default mode when FGC happens

**Steps to Reproduce**
1. Specify -XX:+HeapDumpBeforeFullGC
2. Run the app until FGC

**Expected behavior**
Full heap dump generated

**JDK version**
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.0.0-b49) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.0.0-b49) (build 25.212-b04, mixed mode)

**Execution environment**
 - OS and version: Linux
 - CPU model: x64
 - Number of CPU cores: any
 - Size of physical memory: any
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by D-D-H** [comment]
looks good.
