### ISSUE TITLE
[Bug] 开启wisp使用lettuce时无法启动成功

### ISSUE THREAD

**Issue by halfciga** [alibaba/dragonwell8#467]
开启了wisp后，使用lettuce组件的情况下，springboot无法正常启动，jstack发现main线程卡住在WAITING状态
[1.txt](https://github.com/alibaba/dragonwell8/files/10684258/1.txt)

**Comment by Clownsw** [comment]
-Dio.netty.transport.noNative=true

**Comment by Clownsw** [comment]
[https://github.com/alibaba/dragonwell8/wiki/Wisp%E6%96%87%E6%A1%A3#faq](https://github.com/alibaba/dragonwell8/wiki/Wisp%E6%96%87%E6%A1%A3#faq)
