### ISSUE TITLE
[Misc] upgrade java -version output to match 222u-b10

### ISSUE THREAD

**Issue by shiyuexw** [alibaba/dragonwell8#49]
Description

dragonwell8 is ready synchronized with openjdk upstream 222u-b10. 
java -version should match it.

Steps to Reproduce

Run "java -version"
The output still show that the build is still from 212-b04
Expected behavior
java -version should have the following output

openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.0.0-b00) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.0.0-b00) (build 25.222-b10, mixed mode)

JDK version
latest

Execution environment
any

**Comment by luchsh** [comment]
@shiyuexw  can we close this issue now?

**Comment by shiyuexw** [comment]
push the commit.
