### ISSUE TITLE
[docker hub] docker hub 上的账户 alibabadragonwell 是你们官方的吗？

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [alibaba/dragonwell8#511]
docker hub 网站上的用户：https://hub.docker.com/u/alibabadragonwell

请问这个用户是你们官方的吗？发布的镜像是官方镜像？

**Comment by zhengxiaolinX** [comment]
是官方的镜像。Latest 的话可以
```
alibabadragonwell/dragonwell:8-ubuntu
alibabadragonwell/dragonwell:8-centos
alibabadragonwell/dragonwell:8-anolis
```
来简单指定 Dragonwell8 + Base OS。如果想要具体版本的话可以在 tags [1] 中搜索。
Docker hub 的描述我们还在完善中。

[1] https://hub.docker.com/r/alibabadragonwell/dragonwell/tags

**Comment by xuxiaowei-com-cn** [comment]
谢谢

**Comment by xuxiaowei-com-cn** [comment]
刚才发布议题前，使用 alibabadragonwell/dragonwell:8-stanard-ga-anolis-x86_64 ，发现有问题，无法创建容器

**Comment by zhengxiaolinX** [comment]
感谢反馈，的确存在这个问题，有问题的镜像已经修复掉了。这个镜像的 tag 的 `stanard` 少了个 d，实际上应该是 `standard`。
后边我们会清理一遍单 arch 的镜像，把带 `-x86_64` 的这种都清除掉。后边用户直接用类似 `alibabadragonwell/dragonwell:8-standard-ga-anolis` 的 multiarch tag 就可以在不同平台上使用了。
