### ISSUE TITLE
OpenJDK 8 broken font rendering e.g. for Google font "Great Vibes"

### ISSUE THREAD

**Issue by BuZZ-dEE** [alibaba/dragonwell8#58]
**Platform:**
 Fedora release 30 (Thirty), Debian GNU/Linux 9.9 (stretch), Ubuntu 18.04, Arch Linux
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.0.0-b03) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.0.0-b03) (build 25.212-b04, mixed mode)

**Architecture:**
amd64

Please see the following images for Google font "[Great Vibes](https://fonts.google.com/specimen/Great+Vibes)":

**OpenJDK 8** **_broken_** font redering:

![openjdk-8-font-incorrect](https://user-images.githubusercontent.com/125954/67096926-6529e900-f1b9-11e9-82ba-1e672216225d.png)

![openjdk-8-font-incorrect-marked](https://user-images.githubusercontent.com/125954/67101295-a58d6500-f1c1-11e9-9cc8-8dc72eb6da19.png)

**OracleJDK 8, OpenJDK 10, 11, 13** correct font rendering:

![openjdk-13-font-correct](https://user-images.githubusercontent.com/125954/67096942-6d822400-f1b9-11e9-8f39-43175ffe1189.png)

**Example code**:

Wrong rendering **_not_** visible:
```java
javax.swing.JButton button = new javax.swing.JButton("Open");
java.awt.Font font = new java.awt.Font("Great Vibes", Font.PLAIN, 64);
button.setFont(font);
```
![OpenJDK-8-font-size-128-wrong-rendering-not-visible png](https://user-images.githubusercontent.com/125954/67099592-8b05bc80-f1be-11e9-995b-b535ac0dda12.png)

Wrong rendering visible:
```java
javax.swing.JButton button = new javax.swing.JButton("Open");
java.awt.Font font = new java.awt.Font("Great Vibes", Font.PLAIN, 128);
button.setFont(font);
```
![OpenJDK-8-font-size-128-wrong-rendering-visible](https://user-images.githubusercontent.com/125954/67099600-8e994380-f1be-11e9-8c5a-024eb3b1809b.png)

As it turned out, it is related to the [font version](https://github.com/corretto/corretto-8/files/3748490/Great.Vibes.ttf.zip) we are using.:
* [broken font version:](https://github.com/corretto/corretto-8/files/3748490/Great.Vibes.ttf.zip)
* [correct font version](https://github.com/corretto/corretto-8/files/3748496/greatvibes.zip) downloaded from [here](https://github.com/google/fonts/archive/master.zip)

**Comment by luchsh** [comment]
Thanks for reporting this issue!

The Dragonwell 8.1.1GA build just came out last week, does it work for this issue?

If not, I'd like to suggest you raise a bug for upstream JDK: https://bugs.openjdk.java.net
Because so far as I know Dragonwell has not merged any patches for the client libraries (swing, awt, etc.), at present we are focusing on the backend.

**Comment by BuZZ-dEE** [comment]
https://github.com/corretto/corretto-8/issues/176

**Comment by BuZZ-dEE** [comment]
As far as I can see I can not raise a bug in the OpenJDK bugtracker
