### ISSUE TITLE
什么时候开放wisp2

### ISSUE THREAD

**Issue by alexliu123456** [alibaba/dragonwell8#61]
什么时候开放wisp2

**Comment by luchsh** [comment]
Thanks for asking!
1, Please use Dragonwell issue template to submit issues,
 and you can join our Dingtalk group for formal/informal discussions.
2, It may be shipped with Dragonwell in 2020, but sorry I don't have a specific date yet.

**Comment by yansendao** [comment]
> Thanks for asking!
> 1, Please use Dragonwell issue template to submit issues,
> and you can join our Dingtalk group for formal/informal discussions.
> 2, It may be shipped with Dragonwell in 2020, but sorry I don't have a specific date yet.

How can I join Dingtalk group for formal/informal?

**Comment by yansendao** [comment]
How can I join Dingtalk group for formal/informal?
