### ISSUE TITLE
编译问题 

### ISSUE THREAD

**Issue by sc-ik** [alibaba/dragonwell8#68]
/home/sc-ik/Downloads/dragonwell8/hotspot/src/share/vm/gc_implementation/g1/elasticHeap.cpp: In static member function ‘static bool ElasticHeapTimer::has_error(Thread*, const char*)’:
/home/sc-ik/Downloads/dragonwell8/hotspot/src/share/vm/gc_implementation/g1/elasticHeap.cpp:293:24: error: format not a string literal and no format arguments [-Werror=format-security]
     tty->print_cr(error);
                        ^
cc1plus: all warnings being treated as errors
make[6]: *** [elasticHeap.o] Error 1
make[5]: *** [the_vm] Error 2
make[4]: *** [debug] Error 2
make[3]: *** [generic_build2] Error 2
make[2]: *** [debug] Error 2
make[1]: *** [/home/sc-ik/Downloads/dragonwell8/build/linux-x86_64-normal-server-slowdebug/hotspot/_hotspot.timestamp] Error 2

**Comment by luchsh** [comment]
Thanks for reporting!
Could you pls provide more information? such as compiler name, version, os version, etc
btw, pls use the Dragonwell issue template.

**Comment by sc-ik** [comment]
> 感谢您的举报！
> 您能否提供更多信息？例如编译器名称，版本，操作系统版本等
> ，请使用Dragonwell问题模板。

**Description**
我是在虚拟机中安装 ubuntu 14.04.6 进行编译.

**Steps to Reproduce**
1. chmod +x ./configure
2. ./configure --with-target-bits=64 --with-boot-jdk=/home/123/Downloads/jdk1.7.0_80 --with-debug-level=slowdebug --enable-debug-symbols ZIP_DEBUGINFO_FILES=0

**JDK version**
Alibaba Dragonwell 8.1.1 GA

**Execution environment**
 - gcc version = 4.8.4
 - ubuntu version="14.04.6 LTS, Trusty Tahr"
 - Number of CPU cores: 2
 - Size of physical memory: 1G



可以在 https://mirrors.163.com/ubuntu-releases/14.04/ 中下载   ubuntu-14.04.6-desktop-amd64.iso

**Comment by luchsh** [comment]
@mmyxym  ElasticHeap related, please take a look.

**Comment by sc-ik** [comment]
麻烦能活跃以下吗?

**Comment by mmyxym** [comment]
> 麻烦能活跃以下吗?

If you want to make debug build for debugging, can you please try
./make.sh debug --disable-zip-debug-info

**Comment by sc-ik** [comment]
> > 麻烦能活跃以下吗?
> 
> If you want to make debug build for debugging, can you please try
> ./make.sh debug --disable-zip-debug-info

一样的问题 不一样的心情 

/dragonwell8/hotspot/src/share/vm/gc_implementation/g1/elasticHeap.cpp:293:24: error: format not a string literal and no format arguments [-Werror=format-security]
     tty->print_cr(error);
                        ^
cc1plus: all warnings being treated as errors
make[6]: *** [elasticHeap.o] Error 1
make[6]: Leaving directory `/home/sc-ik/sss/dragonwell8/build/linux-x86_64-normal-server-slowdebug/hotspot/linux_amd64_compiler2/debug'
make[5]: *** [the_vm] Error 2
make[5]: Leaving directory `/home/sc-ik/sss/dragonwell8/build/linux-x86_64-normal-server-slowdebug/hotspot/linux_amd64_compiler2/debug'
make[4]: Leaving directory `/home/sc-ik/sss/dragonwell8/build/linux-x86_64-normal-server-slowdebug/hotspot'
make[4]: *** [debug] Error 2
make[3]: *** [generic_build2] Error 2
make[3]: Leaving directory `/home/sc-ik/sss/dragonwell8/hotspot/make'
make[2]: *** [debug] Error 2
make[2]: Leaving directory `/home/sc-ik/sss/dragonwell8/hotspot/make'
make[1]: *** [/home/sc-ik/sss/dragonwell8/build/linux-x86_64-normal-server-slowdebug/hotspot/_hotspot.timestamp] Error 2
make[1]: Leaving directory `/home/sc-ik/sss/dragonwell8/make'
make: *** [hotspot-only] Error 2

**Comment by luchsh** [comment]
> > > 麻烦能活跃以下吗?
> > 
> > 
> > If you want to make debug build for debugging, can you please try
> > ./make.sh debug --disable-zip-debug-info
> 
> 一样的问题 不一样的心情
> 
> /dragonwell8/hotspot/src/share/vm/gc_implementation/g1/elasticHeap.cpp:293:24: error: format not a string literal and no format arguments [-Werror=format-security]
> tty->print_cr(error);
> 
> cc1plus: all warnings being treated as errors
> make[6]: *** [elasticHeap.o] Error 1
> make[6]: Leaving directory `/home/sc-ik/sss/dragonwell8/build/linux-x86_64-normal-server-slowdebug/hotspot/linux_amd64_compiler2/debug' make[5]: *** [the_vm] Error 2 make[5]: Leaving directory `/home/sc-ik/sss/dragonwell8/build/linux-x86_64-normal-server-slowdebug/hotspot/linux_amd64_compiler2/debug'
> make[4]: Leaving directory `/home/sc-ik/sss/dragonwell8/build/linux-x86_64-normal-server-slowdebug/hotspot' make[4]: *** [debug] Error 2 make[3]: *** [generic_build2] Error 2 make[3]: Leaving directory `/home/sc-ik/sss/dragonwell8/hotspot/make'
> make[2]: *** [debug] Error 2
> make[2]: Leaving directory `/home/sc-ik/sss/dragonwell8/hotspot/make' make[1]: *** [/home/sc-ik/sss/dragonwell8/build/linux-x86_64-normal-server-slowdebug/hotspot/_hotspot.timestamp] Error 2 make[1]: Leaving directory `/home/sc-ik/sss/dragonwell8/make'
> make: *** [hotspot-only] Error 2
> 
> 麻烦你们能写一个详细的编译文档, 方便我这种 菜鸟吗?

The build instructions are in `./README-builds.html`, pls have a look.
Thanks

**Comment by sc-ik** [comment]
@luchsh  我已经解决了

貌似和 gcc 有关系, 我使用ubuntu 就没法编译  但是 使用 centos 7.3 就可以 

其中 gcc 版本是 gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC)

**Comment by sc-ik** [comment]
我还是写了一遍关于编译的教程.

[编译 Alibaba Dragonwell 8.1.1 GA] (https://www.yuque.com/xiangpica-9ve1w/bivz7w/ocoxy5)

在这里插个眼, 在编译时有人遇到问题可以做参考😁
