### ISSUE TITLE
[Misc] Build fails after rebasing 8u232, fix it by porting 8202353 from upstream

### ISSUE THREAD

**Issue by zhengxiaolinX** [alibaba/dragonwell8#73]
**Description**
8u232 changed the api `os::readdir`, which is not compatible with the jfr patch.

**Steps to Reproduce**
run configure and make images

**Expected behavior**
pass the building phase and all jfr tests

**JDK version**
On latest 8u222-GA

**Execution environment**
 - OS and version: Linux, x64
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container?
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by luchsh** [comment]
please add the links to upstream bug and patch, thanks

**Comment by zhengxiaolinX** [comment]
> please add the links to upstream bug and patch, thanks

Buglist ref: https://bugs.openjdk.java.net/browse/JDK-8202353
Fix ref: http://hg.openjdk.java.net/jdk/jdk/rev/f605c91e5219
