### ISSUE TITLE
[Bug] Support linux 5.0 kernel please

### ISSUE THREAD

**Issue by netroby** [alibaba/dragonwell8#8]
I tried compile dragonwell8 from source code, but failed to compile.
Seems not support linux kernel 5.0+

**Comment by luchsh** [comment]
Could you please share the details of failure?
JDK rarely has got dependencies on Linux kernel directly.

**Comment by netroby** [comment]
Seems it cause by the glibc , ubuntu 18.10 , with glibc version  2.58.1-2
