### ISSUE TITLE
[Incompatible]使用Alibaba Dragonwell，Activiti流程图不能显示中文(宋体)

### ISSUE THREAD

**Issue by cszyx666** [alibaba/dragonwell8#98]
**Description**
使用Alibaba Dragonwell作为jvm环境，Activiti流程图不能显示中文(宋体)。
![image](https://user-images.githubusercontent.com/48897647/79934313-d3ab7480-8484-11ea-8738-7afc83333349.png)

**Steps to Reproduce**
本人进入docker容器后发现Dragonwell中删除了fonts文件夹等对字体支持的部分，请问Dragonwell是否在主程序中保留Openjdk的font.manager的支持，若不支持能否推荐一些关于字体正确显示的办法。

**Expected behavior**
希望能够支持中文字体

**JDK version**
Dragonwell8

**Execution environment**
 - centos7
 - docker-ci 19.03

**Comment by luchsh** [comment]
Thanks for reporting!

May I ask if you have got a test case to reproduce this issue?
and can you pls share it with us?

**Comment by cszyx666** [comment]
![image](https://user-images.githubusercontent.com/48897647/79937142-b3cb7f00-848b-11ea-9b1b-6f32f7e843b4.png)

**Comment by cszyx666** [comment]
我是用的Activiti版本是5.22.0

**Comment by cszyx666** [comment]
我看看能不能把镜像上传到docker hub，你们可以下载来看

**Comment by luchsh** [comment]
For font rendering, Dragonwell 8.3.3 shares almost the same code base with OpenJDK 8u242; 

May I ask several questions?
- Does it work for other non-java applications to display Chinese characters?
- Have you tried OpenJDK8u to see if it works?

**Comment by luchsh** [comment]
In DingTalk group, I saw you had got a solution by installing missing font packages.
So I'm closing this issue now, please re-open if you feel necessary.

**Comment by hanlukk** [comment]
请问怎么解决的？？
